// <auto-generated />
using System;
using InvestmentApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentApp.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230520185354_coin_property")]
    partial class coin_property
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InvestmentApp.API.Models.Coin", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AllTimeHighUSD")
                        .HasColumnType("float");

                    b.Property<double>("Cap")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<string>("png64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Uid = "05a9c8fb-c9f1-46e5-995b-c8992955ece1",
                            Age = "5213",
                            AllTimeHighUSD = 68781.0,
                            Cap = 586709801651.0,
                            Code = "BTC",
                            Name = "Bitcoin",
                            Rank = 1,
                            Rate = 30328.198749641579,
                            Volume = 12110337907.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btc.png"
                        },
                        new
                        {
                            Uid = "a1020fac-d153-40be-a4be-e0ec65fa2f39",
                            Age = "2814",
                            AllTimeHighUSD = 4861.0,
                            Cap = 245902442713.0,
                            Code = "ETH",
                            Name = "Ethereum",
                            Rank = 2,
                            Rate = 2009.4359257497333,
                            Volume = 11770158389.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eth.png"
                        },
                        new
                        {
                            Uid = "2d8d7d12-6b26-4c89-ace2-dd572a5ec1c9",
                            Age = "3208",
                            AllTimeHighUSD = 1.0,
                            Cap = 80650366506.0,
                            Code = "USDT",
                            Name = "Tether",
                            Rank = 3,
                            Rate = 1.0008881832810113,
                            Volume = 29981592764.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdt.png"
                        },
                        new
                        {
                            Uid = "aa83ac91-d698-4f8b-a114-d6bb12302564",
                            Age = "2112",
                            AllTimeHighUSD = 692.0,
                            Cap = 51303060046.0,
                            Code = "BNB",
                            Name = "BNB",
                            Rank = 4,
                            Rate = 326.31460014781129,
                            Volume = 601475322.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bnb.png"
                        },
                        new
                        {
                            Uid = "e5d4e522-e2ae-4be8-94ee-fe841e842e02",
                            Age = "1647",
                            AllTimeHighUSD = 1.0,
                            Cap = 31890674516.0,
                            Code = "USDC",
                            Name = "USD Coin",
                            Rank = 5,
                            Rate = 0.99906956237183553,
                            Volume = 2131442649.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdc.png"
                        },
                        new
                        {
                            Uid = "c95b064b-4ed5-466d-a4ed-8221a5210a5f",
                            Age = "4120",
                            AllTimeHighUSD = 4.0,
                            Cap = 26621449102.0,
                            Code = "XRP",
                            Name = "XRP",
                            Rank = 6,
                            Rate = 0.51441608174902442,
                            Volume = 924923532.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xrp.png"
                        },
                        new
                        {
                            Uid = "64275ee9-6a30-4389-8b0f-629c6e0af94e",
                            Age = "2019",
                            AllTimeHighUSD = 3.0,
                            Cap = 14892005010.0,
                            Code = "ADA",
                            Name = "Cardano",
                            Rank = 7,
                            Rate = 0.42493925406676497,
                            Volume = 400520948.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ada.png"
                        },
                        new
                        {
                            Uid = "18544b73-a5c1-44b9-9293-e45c7cfc9300",
                            Age = "3405",
                            AllTimeHighUSD = 1.0,
                            Cap = 11522625745.0,
                            Code = "DOGE",
                            Name = "Dogecoin",
                            Rank = 8,
                            Rate = 0.086851280356138386,
                            Volume = 580249613.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/doge.png"
                        },
                        new
                        {
                            Uid = "7fd18b1d-123b-42f8-b69f-628eaf574eec",
                            Age = "1443",
                            AllTimeHighUSD = 59.0,
                            Cap = 10454208201.0,
                            Code = "OKB",
                            Name = "OKB",
                            Rank = 9,
                            Rate = 43.296753238680481,
                            Volume = 10300220.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/okb.png"
                        },
                        new
                        {
                            Uid = "e96ef314-2089-4505-afbb-86cbc7fefb52",
                            Age = "1445",
                            AllTimeHighUSD = 3.0,
                            Cap = 10422239560.0,
                            Code = "MATIC",
                            Name = "Polygon",
                            Rank = 10,
                            Rate = 1.1304598432321304,
                            Volume = 277086510.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/matic.png"
                        },
                        new
                        {
                            Uid = "d320f7c0-e1f1-4da6-b8d5-44df56d0c467",
                            Age = "1096",
                            AllTimeHighUSD = 260.0,
                            Cap = 9643105628.0,
                            Code = "SOL",
                            Name = "Solana",
                            Rank = 11,
                            Rate = 24.622276579457843,
                            Volume = 599873521.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sol.png"
                        },
                        new
                        {
                            Uid = "dc26dc81-e81b-4b3d-8867-d3435124c7c5",
                            Age = "1933",
                            AllTimeHighUSD = 1.0,
                            Cap = 9349403278.0,
                            Code = "DAI",
                            Name = "Dai",
                            Rank = 12,
                            Rate = 0.99896975301912971,
                            Volume = 145345881.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dai.png"
                        },
                        new
                        {
                            Uid = "c5044185-12d2-4b2d-86c9-db5e8a20575d",
                            Age = "963",
                            AllTimeHighUSD = 55.0,
                            Cap = 7216234937.0,
                            Code = "DOT",
                            Name = "Polkadot",
                            Rank = 13,
                            Rate = 6.5941059350564526,
                            Volume = 196136715.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dot.png"
                        },
                        new
                        {
                            Uid = "98e37769-7070-4832-bee7-c343493bf769",
                            Age = "4205",
                            AllTimeHighUSD = 413.0,
                            Cap = 6867505577.0,
                            Code = "LTC",
                            Name = "Litecoin",
                            Rank = 14,
                            Rate = 94.466823379278523,
                            Volume = 506762508.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ltc.png"
                        },
                        new
                        {
                            Uid = "346a11b8-2bce-4317-8566-27188520df4f",
                            Age = "1301",
                            AllTimeHighUSD = 1.0,
                            Cap = 6753399417.0,
                            Code = "BUSD",
                            Name = "Binance USD",
                            Rank = 15,
                            Rate = 1.0019091540080731,
                            Volume = 2131249600.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/busd.png"
                        },
                        new
                        {
                            Uid = "4acfd8ea-f1f1-43ce-b14b-ecbbe57f8ef6",
                            Age = "799",
                            AllTimeHighUSD = 0.0,
                            Cap = 6529338418.0,
                            Code = "SHIB",
                            Name = "Shiba Inu",
                            Rank = 16,
                            Rate = 1.1079815049231357E-05,
                            Volume = 177337714.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/shib.png"
                        },
                        new
                        {
                            Uid = "4b8eafee-1899-4c21-ba37-75057404f7f8",
                            Age = "933",
                            AllTimeHighUSD = 146.0,
                            Cap = 6153496756.0,
                            Code = "AVAX",
                            Name = "Avalanche",
                            Rank = 17,
                            Rate = 18.864857950030537,
                            Volume = 273147965.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/avax.png"
                        },
                        new
                        {
                            Uid = "02b6517f-7b12-40ea-9dd0-69c4a5cbc070",
                            Age = "2038",
                            AllTimeHighUSD = 0.0,
                            Cap = 6025817589.0,
                            Code = "TRX",
                            Name = "TRON",
                            Rank = 18,
                            Rate = 0.066335058912063344,
                            Volume = 181564796.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/trx.png"
                        },
                        new
                        {
                            Uid = "4aabac95-637b-4865-b5a9-c94a43dd1f6e",
                            Age = "21",
                            AllTimeHighUSD = 12.0,
                            Cap = 5445384888.0,
                            Code = "ARB",
                            Name = "Arbitrum",
                            Rank = 19,
                            Rate = 1.3548179589002987,
                            Volume = 1046271860.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/arb.png"
                        },
                        new
                        {
                            Uid = "f8d71971-7c6a-4c63-937d-a2b4078dde7a",
                            Age = "2035",
                            AllTimeHighUSD = 53.0,
                            Cap = 3847806271.0,
                            Code = "LINK",
                            Name = "Chainlink",
                            Rank = 20,
                            Rate = 7.4411264640052144,
                            Volume = 213379211.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/link.png"
                        },
                        new
                        {
                            Uid = "b0e243e3-6161-4f4e-9a13-a0287164c36e",
                            Age = "1532",
                            AllTimeHighUSD = 69231.0,
                            Cap = 3594285291.0,
                            Code = "WBTC",
                            Name = "Wrapped Bitcoin",
                            Rank = 21,
                            Rate = 30387.424050003468,
                            Volume = 210801018.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/wbtc.png"
                        },
                        new
                        {
                            Uid = "590fc416-9326-4527-b3ee-de04ce1b3a6b",
                            Age = "2453",
                            AllTimeHighUSD = 169.0,
                            Cap = 3128581467.0,
                            Code = "ETC",
                            Name = "Ethereum Classic",
                            Rank = 22,
                            Rate = 22.275222847304718,
                            Volume = 199755588.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/etc.png"
                        },
                        new
                        {
                            Uid = "451fad4f-6887-4beb-8f52-b1ed72097b76",
                            Age = "3282",
                            AllTimeHighUSD = 517.0,
                            Cap = 2966640940.0,
                            Code = "XMR",
                            Name = "Monero",
                            Rank = 23,
                            Rate = 162.41889788396699,
                            Volume = 70093418.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xmr.png"
                        },
                        new
                        {
                            Uid = "bd2d429c-20ec-4934-a54b-e20a28fe4168",
                            Age = "938",
                            AllTimeHighUSD = 45.0,
                            Cap = 2925381898.0,
                            Code = "UNI",
                            Name = "Uniswap",
                            Rank = 24,
                            Rate = 6.195608698729786,
                            Volume = 99949699.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/uni.png"
                        },
                        new
                        {
                            Uid = "e345ff20-9a4f-4546-99c1-90ca7239a1e3",
                            Age = "2376",
                            AllTimeHighUSD = 44.0,
                            Cap = 2818399814.0,
                            Code = "ATOM",
                            Name = "Cosmos",
                            Rank = 25,
                            Rate = 11.815959899295345,
                            Volume = 127011892.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/atom.png"
                        },
                        new
                        {
                            Uid = "be81d0f2-b6e9-45c7-a5d2-ccf04fa78517",
                            Age = "3172",
                            AllTimeHighUSD = 1.0,
                            Cap = 2803651541.0,
                            Code = "XLM",
                            Name = "Stellar",
                            Rank = 26,
                            Rate = 0.1048605169525406,
                            Volume = 51728530.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xlm.png"
                        },
                        new
                        {
                            Uid = "8ebbf718-8493-4499-8032-de4f9b9cd29b",
                            Age = "2081",
                            AllTimeHighUSD = 4356.0,
                            Cap = 2650155454.0,
                            Code = "BCH",
                            Name = "Bitcoin Cash",
                            Rank = 27,
                            Rate = 136.86199605416891,
                            Volume = 70687185.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bch.png"
                        },
                        new
                        {
                            Uid = "f4bef1bc-5235-4b37-aa5b-083958b4e568",
                            Age = "909",
                            AllTimeHighUSD = 238.0,
                            Cap = 2510872731.0,
                            Code = "FIL",
                            Name = "Filecoin",
                            Rank = 28,
                            Rate = 6.0535867293097585,
                            Volume = 132878881.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/fil.png"
                        },
                        new
                        {
                            Uid = "57570ddf-784e-4987-b07b-d58a70b608ef",
                            Age = "975",
                            AllTimeHighUSD = 14.0,
                            Cap = 2194180620.0,
                            Code = "SRM",
                            Name = "Serum",
                            Rank = 29,
                            Rate = 0.21594670202632751,
                            Volume = 57598923.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/srm.png"
                        },
                        new
                        {
                            Uid = "ef2026d5-69ff-4235-9534-61b76fdc71bd",
                            Age = "827",
                            AllTimeHighUSD = 7.0,
                            Cap = 2091528832.0,
                            Code = "LDO",
                            Name = "Lido DAO",
                            Rank = 30,
                            Rate = 2.4161572053155989,
                            Volume = 123572048.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ldo.png"
                        },
                        new
                        {
                            Uid = "9b8b3664-dff1-41b9-86fb-749291c7d611",
                            Age = "1291",
                            AllTimeHighUSD = 1.0,
                            Cap = 2031619214.0,
                            Code = "HBAR",
                            Name = "Hedera Hashgraph",
                            Rank = 31,
                            Rate = 0.066320362634824354,
                            Volume = 42902466.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/hbar.png"
                        },
                        new
                        {
                            Uid = "f9215702-09d4-456c-a6f4-4838f2e0ae4f",
                            Age = "900",
                            AllTimeHighUSD = 20.0,
                            Cap = 1941871015.0,
                            Code = "NEAR",
                            Name = "NEAR Protocol",
                            Rank = 32,
                            Rate = 2.1966128181102982,
                            Volume = 176283114.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/near.png"
                        },
                        new
                        {
                            Uid = "963ddd19-f69d-4671-8005-87f64d6d3389",
                            Age = "2060",
                            AllTimeHighUSD = 0.0,
                            Cap = 1835849605.0,
                            Code = "VET",
                            Name = "VeChain",
                            Rank = 33,
                            Rate = 0.025318171012815527,
                            Volume = 41907992.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/vet.png"
                        },
                        new
                        {
                            Uid = "07368e28-d8f1-48a3-b87d-f1079670220c",
                            Age = "1492",
                            AllTimeHighUSD = 1.0,
                            Cap = 1742687263.0,
                            Code = "CRO",
                            Name = "Cronos",
                            Rank = 34,
                            Rate = 0.068981764580794316,
                            Volume = 7649509.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cro.png"
                        },
                        new
                        {
                            Uid = "388b1df7-e90a-41a7-a54c-04575df1da7c",
                            Age = "392",
                            AllTimeHighUSD = 27.0,
                            Cap = 1651519237.0,
                            Code = "APE",
                            Name = "ApeCoin",
                            Rank = 35,
                            Rate = 4.4805947930215595,
                            Volume = 197598811.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ape.png"
                        },
                        new
                        {
                            Uid = "f89e4833-3897-4baf-ac15-79ac32209806",
                            Age = "702",
                            AllTimeHighUSD = 495.0,
                            Cap = 1650816962.0,
                            Code = "ICP",
                            Name = "Internet Computer",
                            Rank = 36,
                            Rate = 5.4603279459398069,
                            Volume = 44688712.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/icp.png"
                        },
                        new
                        {
                            Uid = "68cbc61c-162c-4a88-aa1b-fdb54d72f219",
                            Age = "176",
                            AllTimeHighUSD = 20.0,
                            Cap = 1594170040.0,
                            Code = "APT",
                            Name = "Aptos",
                            Rank = 37,
                            Rate = 12.262846463104303,
                            Volume = 310152845.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/apt.png"
                        },
                        new
                        {
                            Uid = "013164e7-9f56-4975-863d-48d356b7baf3",
                            Age = "1391",
                            AllTimeHighUSD = 3.0,
                            Cap = 1575340028.0,
                            Code = "ALGO",
                            Name = "Algorand",
                            Rank = 38,
                            Rate = 0.21861473534216658,
                            Volume = 59994706.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/algo.png"
                        },
                        new
                        {
                            Uid = "fbb6bbab-abfc-4b01-9319-0331d8915abf",
                            Age = "524",
                            AllTimeHighUSD = 9.0,
                            Cap = 1548206265.0,
                            Code = "_IMX",
                            Name = "Immutable X",
                            Rank = 39,
                            Rate = 1.1334500380214361,
                            Volume = 59935349.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_imx.png"
                        },
                        new
                        {
                            Uid = "1ef9dea8-0f63-42ed-944a-ed5ef6d01ecc",
                            Age = "1706",
                            AllTimeHighUSD = 427.0,
                            Cap = 1497475701.0,
                            Code = "QNT",
                            Name = "Quant",
                            Rank = 40,
                            Rate = 124.03778671920671,
                            Volume = 22989970.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/qnt.png"
                        },
                        new
                        {
                            Uid = "7df03f3e-d803-4c74-a1ab-7ecd744c252a",
                            Age = "2111",
                            AllTimeHighUSD = 24.0,
                            Cap = 1394057151.0,
                            Code = "EOS",
                            Name = "EOS",
                            Rank = 41,
                            Rate = 1.2654443359627325,
                            Volume = 164795547.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eos.png"
                        },
                        new
                        {
                            Uid = "3aa993f9-948f-4354-b5c6-1aaf9c9f0c13",
                            Age = "2034",
                            AllTimeHighUSD = 6.0,
                            Cap = 1349697366.0,
                            Code = "MANA",
                            Name = "Decentraland",
                            Rank = 42,
                            Rate = 0.61540675203591522,
                            Volume = 100343643.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mana.png"
                        },
                        new
                        {
                            Uid = "2c4fd392-4ec1-4b3b-af42-f9b55d8e77a7",
                            Age = "847",
                            AllTimeHighUSD = 3.0,
                            Cap = 1327911676.0,
                            Code = "GRT",
                            Name = "The Graph",
                            Rank = 43,
                            Rate = 0.15024820642818762,
                            Volume = 63528779.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/grt.png"
                        },
                        new
                        {
                            Uid = "a8bb2f89-07a7-49eb-a5c7-3b7c56b99315",
                            Age = "1626",
                            AllTimeHighUSD = 3.0,
                            Cap = 1297548084.0,
                            Code = "FTM",
                            Name = "Fantom",
                            Rank = 44,
                            Rate = 0.51061396968355321,
                            Volume = 312600111.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ftm.png"
                        },
                        new
                        {
                            Uid = "30313ba2-54b0-4424-8604-3faf1d2c63f4",
                            Age = "889",
                            AllTimeHighUSD = 165.0,
                            Cap = 1286469629.0,
                            Code = "AXS",
                            Name = "Axie Infinity",
                            Rank = 45,
                            Rate = 8.7608934428342931,
                            Volume = 51937698.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/axs.png"
                        },
                        new
                        {
                            Uid = "6638e068-f038-473e-b32c-349b5436de16",
                            Age = "970",
                            AllTimeHighUSD = 8.0,
                            Cap = 1213382309.0,
                            Code = "SAND",
                            Name = "The Sandbox",
                            Rank = 46,
                            Rate = 0.6665903180573155,
                            Volume = 116041705.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sand.png"
                        },
                        new
                        {
                            Uid = "0d9eb876-3823-4744-bf7f-f37f3737da45",
                            Age = "1198",
                            AllTimeHighUSD = 3.0,
                            Cap = 1204098652.0,
                            Code = "_STX",
                            Name = "Stacks",
                            Rank = 47,
                            Rate = 0.87687742582793438,
                            Volume = 121602900.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_stx.png"
                        },
                        new
                        {
                            Uid = "ad59b60e-10d6-411c-9ebe-c710141d1017",
                            Age = "911",
                            AllTimeHighUSD = 663.0,
                            Cap = 1160144987.0,
                            Code = "AAVE",
                            Name = "Aave",
                            Rank = 48,
                            Rate = 80.770928125200655,
                            Volume = 90749892.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/aave.png"
                        },
                        new
                        {
                            Uid = "8c8dd14b-a8fc-4262-af27-d7f82d22c6ce",
                            Age = "1912",
                            AllTimeHighUSD = 16.0,
                            Cap = 1074858108.0,
                            Code = "THETA",
                            Name = "Theta Network",
                            Rank = 49,
                            Rate = 1.0748581079631161,
                            Volume = 20049268.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/theta.png"
                        },
                        new
                        {
                            Uid = "0090677f-78f6-4879-9ef4-52bf5aec852d",
                            Age = "804",
                            AllTimeHighUSD = 42.0,
                            Cap = 1056339832.0,
                            Code = "FLOW",
                            Name = "Flow",
                            Rank = 50,
                            Rate = 1.0194362398508712,
                            Volume = 23890678.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/flow.png"
                        },
                        new
                        {
                            Uid = "5fe3cbcf-eb4e-498f-aed6-9f5cd7ad3689",
                            Age = "1839",
                            AllTimeHighUSD = 9.0,
                            Cap = 1044099181.0,
                            Code = "XTZ",
                            Name = "Tezos",
                            Rank = 51,
                            Rate = 1.117674002603652,
                            Volume = 13413660.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xtz.png"
                        },
                        new
                        {
                            Uid = "390e6cce-dc0e-4acb-8bd7-bf2ecd9b9114",
                            Age = "951",
                            AllTimeHighUSD = 548.0,
                            Cap = 1036526264.0,
                            Code = "EGLD",
                            Name = "MultiversX",
                            Rank = 52,
                            Rate = 41.016003940720196,
                            Volume = 20727486.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/egld.png"
                        },
                        new
                        {
                            Uid = "02c81351-f156-4a70-8d8a-e9f9650c3d17",
                            Age = "767",
                            AllTimeHighUSD = 4.0,
                            Cap = 971061789.0,
                            Code = "MX",
                            Name = "MX Token",
                            Rank = 53,
                            Rate = 2.2210928294677328,
                            Volume = 11230083.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mx.png"
                        },
                        new
                        {
                            Uid = "7dd76537-ee72-4391-9fbd-0c433b6109d3",
                            Age = "590",
                            AllTimeHighUSD = 3.0,
                            Cap = 950876060.0,
                            Code = "__BIT",
                            Name = "BITDAO",
                            Rank = 54,
                            Rate = 0.52140798636966734,
                            Volume = 4058412.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/__bit.png"
                        },
                        new
                        {
                            Uid = "42971f7b-1b13-487f-9530-a481519d848c",
                            Age = "1658",
                            AllTimeHighUSD = 1.0,
                            Cap = 928656143.0,
                            Code = "USDP",
                            Name = "Pax Dollar",
                            Rank = 55,
                            Rate = 0.99880958981750056,
                            Volume = 423611.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdp.png"
                        },
                        new
                        {
                            Uid = "de18018d-98d0-4dcd-8b4d-1a88fd93ad46",
                            Age = "842",
                            AllTimeHighUSD = 2.0,
                            Cap = 912592048.0,
                            Code = "FRAX",
                            Name = "Frax",
                            Rank = 56,
                            Rate = 0.99870729767877375,
                            Volume = 4632040.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/frax.png"
                        },
                        new
                        {
                            Uid = "9aa689ca-6533-49d6-9d3c-53781ebba0f8",
                            Age = "2406",
                            AllTimeHighUSD = 196.0,
                            Cap = 892570611.0,
                            Code = "NEO",
                            Name = "NEO",
                            Rank = 57,
                            Rate = 12.36252589362473,
                            Volume = 30596279.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/neo.png"
                        },
                        new
                        {
                            Uid = "5415c18a-1574-46de-a7bd-2dd117fdcc68",
                            Age = "1198",
                            AllTimeHighUSD = 62.0,
                            Cap = 880725615.0,
                            Code = "RPL",
                            Name = "Rocket Pool",
                            Rank = 58,
                            Rate = 46.078929767765544,
                            Volume = 15099734.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rpl.png"
                        },
                        new
                        {
                            Uid = "3ab9a703-22df-4879-88a2-51a75b419dd7",
                            Age = "1864",
                            AllTimeHighUSD = 2.0,
                            Cap = 855538288.0,
                            Code = "TUSD",
                            Name = "True USD",
                            Rank = 59,
                            Rate = 0.99974566674995036,
                            Volume = 56647944.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/tusd.png"
                        },
                        new
                        {
                            Uid = "0f184c66-f95b-4d0e-8d03-4bee7ddfbfb2",
                            Age = "1028",
                            AllTimeHighUSD = 9.0,
                            Cap = 843087392.0,
                            Code = "RNDR",
                            Name = "Render Token",
                            Rank = 60,
                            Rate = 1.5876871134321542,
                            Volume = 87863143.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rndr.png"
                        },
                        new
                        {
                            Uid = "60d581ce-bc7a-4eff-b83a-a9d94b2754cd",
                            Age = "1586",
                            AllTimeHighUSD = 29.0,
                            Cap = 831268461.0,
                            Code = "SNX",
                            Name = "Synthetix",
                            Rank = 61,
                            Rate = 2.6283183340026004,
                            Volume = 48403838.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/snx.png"
                        },
                        new
                        {
                            Uid = "1d08789f-e5f6-47ca-9bcc-1225d68aca53",
                            Age = "2276",
                            AllTimeHighUSD = 119.0,
                            Cap = 828116098.0,
                            Code = "LUNC",
                            Name = "Luna Classic",
                            Rank = 62,
                            Rate = 0.00012669284582174738,
                            Volume = 60224966.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/lunc.png"
                        },
                        new
                        {
                            Uid = "953ed8cd-fbe5-40bc-8cae-ba82db942b9b",
                            Age = "970",
                            AllTimeHighUSD = 7.0,
                            Cap = 825120005.0,
                            Code = "CRV",
                            Name = "Curve DAO Token",
                            Rank = 63,
                            Rate = 1.0631347154224129,
                            Volume = 50675677.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/crv.png"
                        },
                        new
                        {
                            Uid = "a6f1316b-b071-477e-b41d-7544cb79ff39",
                            Age = "884",
                            AllTimeHighUSD = 2.0,
                            Cap = 813159667.0,
                            Code = "CFX",
                            Name = "Conflux Token",
                            Rank = 64,
                            Rate = 0.38767397643673057,
                            Volume = 267248994.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cfx.png"
                        },
                        new
                        {
                            Uid = "ecbf07cf-2067-4247-93f3-f00394dbf76c",
                            Age = "586",
                            AllTimeHighUSD = 1.0,
                            Cap = 803419209.0,
                            Code = "XRD",
                            Name = "Radix Native Token",
                            Rank = 65,
                            Rate = 0.079177929219493154,
                            Volume = 16144664.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xrd.png"
                        },
                        new
                        {
                            Uid = "2b3b417a-2631-44da-9611-1f1ec363462c",
                            Age = "742",
                            AllTimeHighUSD = 4.0,
                            Cap = 780230689.0,
                            Code = "_KLAY",
                            Name = "Klaytn",
                            Rank = 66,
                            Rate = 0.25288983619249283,
                            Volume = 96165252.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_klay.png"
                        },
                        new
                        {
                            Uid = "d630a03a-a8d0-492e-ad66-7e5129848a9e",
                            Age = "1894",
                            AllTimeHighUSD = 40.0,
                            Cap = 779841435.0,
                            Code = "HT",
                            Name = "Huobi Token",
                            Rank = 67,
                            Rate = 3.8257985724268013,
                            Volume = 16402020.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ht.png"
                        },
                        new
                        {
                            Uid = "857c13e1-547c-41fa-887a-f4a422bcdcd3",
                            Age = "941",
                            AllTimeHighUSD = 13.0,
                            Cap = 774577600.0,
                            Code = "GT",
                            Name = "Gatechain Token",
                            Rank = 68,
                            Rate = 5.4945079961524126,
                            Volume = 508581.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/gt.png"
                        },
                        new
                        {
                            Uid = "5921c749-6563-471e-ad65-7ad5e47251f1",
                            Age = "2264",
                            AllTimeHighUSD = 6299.0,
                            Cap = 730593589.0,
                            Code = "MKR",
                            Name = "Maker",
                            Rank = 69,
                            Rate = 747.31017008504386,
                            Volume = 32172507.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mkr.png"
                        },
                        new
                        {
                            Uid = "6fbbcdde-1cc0-4f36-9b3f-9cf9701716d5",
                            AllTimeHighUSD = 15.0,
                            Cap = 730176154.0,
                            Code = "WBT",
                            Name = "WhiteBIT Token",
                            Rank = 70,
                            Rate = 4.8137561350336462,
                            Volume = 2385277.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/wbt.png"
                        },
                        new
                        {
                            Uid = "a55241e3-a373-4037-9f63-cc9128d57e77",
                            Age = "2356",
                            AllTimeHighUSD = 2218.0,
                            Cap = 728613411.0,
                            Code = "ZEC",
                            Name = "Zcash",
                            Rank = 71,
                            Rate = 44.622822872541775,
                            Volume = 67990465.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/zec.png"
                        },
                        new
                        {
                            Uid = "75e6c1c5-e076-4b96-9c91-5d171130d8ea",
                            Age = "345",
                            AllTimeHighUSD = 1.0,
                            Cap = 718573479.0,
                            Code = "USDD",
                            Name = "Decentralized USD",
                            Rank = 72,
                            Rate = 0.99068212104553866,
                            Volume = 19909392.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdd.png"
                        },
                        new
                        {
                            Uid = "e4d89223-fff6-4efe-b18f-876809e35e15",
                            Age = "1610",
                            AllTimeHighUSD = 491.0,
                            Cap = 700363684.0,
                            Code = "BSV",
                            Name = "Bitcoin SV",
                            Rank = 73,
                            Rate = 36.352170713002614,
                            Volume = 13024930.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bsv.png"
                        },
                        new
                        {
                            Uid = "ef0a469d-da2a-4af3-84a9-9703f6a5a363",
                            Age = "1372",
                            AllTimeHighUSD = 1.0,
                            Cap = 699581929.0,
                            Code = "CHZ",
                            Name = "Chiliz",
                            Rank = 74,
                            Rate = 0.13090821005850312,
                            Volume = 79719095.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/chz.png"
                        },
                        new
                        {
                            Uid = "59e881c1-a4eb-4946-9e56-3654af771940",
                            Age = "727",
                            AllTimeHighUSD = 188.0,
                            Cap = 694182713.0,
                            Code = "MINA",
                            Name = "Mina Protocol",
                            Rank = 75,
                            Rate = 0.78559999246932066,
                            Volume = 48803309.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mina.png"
                        },
                        new
                        {
                            Uid = "3bf27b66-529c-4232-83db-61ae649366f3",
                            Age = "916",
                            AllTimeHighUSD = 44.0,
                            Cap = 677474395.0,
                            Code = "CAKE",
                            Name = "PancakeSwap",
                            Rank = 76,
                            Rate = 3.6559057060612723,
                            Volume = 52025532.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cake.png"
                        },
                        new
                        {
                            Uid = "5cf70210-52ed-4f5e-b574-6f57d10a54d6",
                            Age = "1996",
                            AllTimeHighUSD = 28.0,
                            Cap = 668334731.0,
                            Code = "KCS",
                            Name = "KuCoin Shares",
                            Rank = 77,
                            Rate = 8.8355279000857276,
                            Volume = 1364003.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kcs.png"
                        },
                        new
                        {
                            Uid = "af9720a0-9124-4ef8-9015-c9129f745e6a",
                            Age = "1189",
                            AllTimeHighUSD = 0.0,
                            Cap = 665049722.0,
                            Code = "_SURE",
                            Name = "inSure",
                            Rank = 78,
                            Rate = 0.0076776003523308248,
                            Volume = 3034637.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_sure.png"
                        },
                        new
                        {
                            Uid = "0437cf01-bd19-4c86-bbc9-8ddf3c1b88a8",
                            Age = "3344",
                            AllTimeHighUSD = 1642.0,
                            Cap = 651136662.0,
                            Code = "DASH",
                            Name = "Dash",
                            Rank = 79,
                            Rate = 57.983550702574263,
                            Volume = 65698320.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dash.png"
                        },
                        new
                        {
                            Uid = "756bff71-8b3f-4ce8-ab65-ccb0cdd80210",
                            Age = "563",
                            AllTimeHighUSD = 86.0,
                            Cap = 647976770.0,
                            Code = "__GMX",
                            Name = "GMX",
                            Rank = 80,
                            Rate = 81.073507988673299,
                            Volume = 38651507.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/__gmx.png"
                        },
                        new
                        {
                            Uid = "fb5a9d67-c3e3-47c6-9890-19e0bbe13e7a",
                            Age = "842",
                            AllTimeHighUSD = 45.0,
                            Cap = 646351012.0,
                            Code = "FXS",
                            Name = "Frax Share",
                            Rank = 81,
                            Rate = 9.0715358525988101,
                            Volume = 24544289.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/fxs.png"
                        },
                        new
                        {
                            Uid = "ce310162-4af6-4ae8-b06d-c22459f9a754",
                            Age = "2129",
                            AllTimeHighUSD = 6.0,
                            Cap = 617694856.0,
                            Code = "MIOTA",
                            Name = "IOTA",
                            Rank = 82,
                            Rate = 0.22222994285848705,
                            Volume = 5754165.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/miota.png"
                        },
                        new
                        {
                            Uid = "8dbdeb78-ef27-41c8-95fe-15f1b3e74fc9",
                            Age = "650",
                            AllTimeHighUSD = 0.0,
                            Cap = 615081473.0,
                            Code = "XEC",
                            Name = "eCash",
                            Rank = 83,
                            Rate = 3.1770908082477563E-05,
                            Volume = 4034928.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xec.png"
                        },
                        new
                        {
                            Uid = "4ca0c18c-7188-4460-b5a5-6699c8bc5833",
                            Age = "1838",
                            AllTimeHighUSD = 0.0,
                            Cap = 592646573.0,
                            Code = "XDC",
                            Name = "XDC Network",
                            Rank = 84,
                            Rate = 0.042856757030258409,
                            Volume = 3944111.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xdc.png"
                        },
                        new
                        {
                            Uid = "31a60933-2583-45be-b096-a32019825016",
                            Age = "1532",
                            AllTimeHighUSD = 0.0,
                            Cap = 588833375.0,
                            Code = "BTT",
                            Name = "BitTorrent",
                            Rank = 85,
                            Rate = 6.1889839871637984E-07,
                            Volume = 9281947.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btt.png"
                        },
                        new
                        {
                            Uid = "d05629c4-58ae-4811-9b3e-f3787e6e2211",
                            Age = "322",
                            AllTimeHighUSD = 0.0,
                            Cap = 583907727.0,
                            Code = "KAS",
                            Name = "Kaspa",
                            Rank = 86,
                            Rate = 0.032612547915839396,
                            Volume = 18569847.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kas.png"
                        },
                        new
                        {
                            Uid = "527a59c4-f219-4894-95dc-186c4defd939",
                            Age = "1359",
                            AllTimeHighUSD = 21.0,
                            Cap = 549835701.0,
                            Code = "RUNE",
                            Name = "THORChain",
                            Rank = 87,
                            Rate = 1.6321258352499231,
                            Volume = 31640143.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rune.png"
                        },
                        new
                        {
                            Uid = "d95aafed-4397-46c9-9f32-72691b233429",
                            Age = "903",
                            AllTimeHighUSD = 25.0,
                            Cap = 537776849.0,
                            Code = "INJ",
                            Name = "Injective Protocol",
                            Rank = 88,
                            Rate = 6.7217437819127657,
                            Volume = 107047190.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/inj.png"
                        },
                        new
                        {
                            Uid = "e79a1102-0524-4372-aefb-5ed019696e22",
                            Age = "675",
                            AllTimeHighUSD = 0.0,
                            Cap = 537254667.0,
                            Code = "BABYDOGE",
                            Name = "Baby Doge Coin",
                            Rank = 89,
                            Rate = 2.4980008270697834E-09,
                            Volume = 10275593.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/babydoge.png"
                        },
                        new
                        {
                            Uid = "01fd0241-9735-4619-b000-bb4321a778a2",
                            Age = "520",
                            AllTimeHighUSD = 84.0,
                            Cap = 532259706.0,
                            Code = "ENS",
                            Name = "Ethereum Name Service",
                            Rank = 90,
                            Rate = 13.590619143368228,
                            Volume = 27588209.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ens.png"
                        },
                        new
                        {
                            Uid = "d55f23ec-2e2b-42d6-8f80-f195c366c939",
                            Age = "1295",
                            AllTimeHighUSD = 2222.0,
                            Cap = 527549554.0,
                            Code = "PAXG",
                            Name = "PAX Gold",
                            Rank = 91,
                            Rate = 2042.9919540285246,
                            Volume = 14703777.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/paxg.png"
                        },
                        new
                        {
                            Uid = "1937ff3f-98f0-48cf-84ce-f600092764e7",
                            Age = "316",
                            AllTimeHighUSD = 3.0,
                            Cap = 523108103.0,
                            Code = "OP",
                            Name = "Optimism",
                            Rank = 92,
                            Rate = 2.4359119352872192,
                            Volume = 169354388.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/op.png"
                        },
                        new
                        {
                            Uid = "ec1528f3-e8ad-4595-9ee2-7966e77fb407",
                            Age = "675",
                            AllTimeHighUSD = 1.0,
                            Cap = 486891673.0,
                            Code = "AGIX",
                            Name = "SingularityNET",
                            Rank = 93,
                            Rate = 0.40368364922792982,
                            Volume = 65325438.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/agix.png"
                        },
                        new
                        {
                            Uid = "1dd5e531-26b3-4c4f-8a5f-3bb453b273e1",
                            Age = "2051",
                            AllTimeHighUSD = 4.0,
                            Cap = 484033579.0,
                            Code = "LRC",
                            Name = "Loopring",
                            Rank = 94,
                            Rate = 0.36153227169751667,
                            Volume = 26078150.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/lrc.png"
                        },
                        new
                        {
                            Uid = "eaa60334-673e-42d4-a5e9-a9bdad917d00",
                            Age = "706",
                            AllTimeHighUSD = 40.0,
                            Cap = 483242748.0,
                            Code = "CSPR",
                            Name = "Casper Network",
                            Rank = 95,
                            Rate = 0.044268223688168698,
                            Volume = 7331958.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cspr.png"
                        },
                        new
                        {
                            Uid = "d8a7ca70-b74d-4cec-b940-4e64f6633d31",
                            Age = "618",
                            AllTimeHighUSD = 11.0,
                            Cap = 454317232.0,
                            Code = "OSMO",
                            Name = "Osmosis",
                            Rank = 96,
                            Rate = 0.80657164263503145,
                            Volume = 10831520.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/osmo.png"
                        },
                        new
                        {
                            Uid = "65a334e0-0be3-426e-91c9-bbdc15d96f58",
                            Age = "1419",
                            AllTimeHighUSD = 0.0,
                            Cap = 451724888.0,
                            Code = "RSR",
                            Name = "Reserve Rights",
                            Rank = 97,
                            Rate = 0.0045180395383625487,
                            Volume = 10588914.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rsr.png"
                        },
                        new
                        {
                            Uid = "7f661f16-c4a0-4146-86bb-5646a747777c",
                            Age = "1198",
                            AllTimeHighUSD = 9.0,
                            Cap = 450724496.0,
                            Code = "KAVA",
                            Name = "Kava",
                            Rank = 98,
                            Rate = 0.94235684969696731,
                            Volume = 16450427.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kava.png"
                        },
                        new
                        {
                            Uid = "17089970-5139-48dd-ab2d-294aa2481f69",
                            Age = "839",
                            AllTimeHighUSD = 9.0,
                            Cap = 443724164.0,
                            Code = "1INCH",
                            Name = "1inch",
                            Rank = 99,
                            Rate = 0.54478528873423893,
                            Volume = 25365079.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/1inch.png"
                        },
                        new
                        {
                            Uid = "57e613ef-8774-456e-a08e-7c6967461668",
                            Age = "693",
                            AllTimeHighUSD = 60.0,
                            Cap = 443590805.0,
                            Code = "CVX",
                            Name = "Convex Finance",
                            Rank = 100,
                            Rate = 5.8113251636007464,
                            Volume = 10949452.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cvx.png"
                        });
                });

            modelBuilder.Entity("InvestmentApp.API.Models.SiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3ad25e9a-7ece-434d-900c-9a67f1be1f66",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c576f03-a3ff-48eb-98b8-b6dce04e722e",
                            Email = "admin@admin.adm",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEIelaZ3P+kBjDlUar0pHeWmSRhecxphjIEQHCVIcCelmDTZvAdPyhe+3K0v1iHB/uA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9b2d1099-bbea-4871-b8a8-c12f95768352",
                            TwoFactorEnabled = false,
                            UserName = "superuser"
                        });
                });

            modelBuilder.Entity("InvestmentApp.API.Models.UserCoins", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoinId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CoinCount")
                        .HasColumnType("float");

                    b.Property<string>("SiteUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "CoinId");

                    b.HasIndex("CoinId");

                    b.HasIndex("SiteUserId");

                    b.ToTable("UserCoins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "I",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InvestmentApp.API.Models.UserCoins", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany("Coins")
                        .HasForeignKey("SiteUserId");

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestmentApp.API.Models.SiteUser", b =>
                {
                    b.Navigation("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
