// <auto-generated />
using System;
using InvestmentApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentApp.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230516203120_simplecoins")]
    partial class simplecoins
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InvestmentApp.API.Models.Coin", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AllTimeHighUSD")
                        .HasColumnType("bigint");

                    b.Property<long>("Cap")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<string>("png64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Uid = "0169c8d9-aa3a-4382-860b-3e06f79ad59b",
                            Age = "5213",
                            AllTimeHighUSD = 68781L,
                            Cap = 586709801651L,
                            Code = "BTC",
                            Name = "Bitcoin",
                            Rank = 1L,
                            Rate = 30328.198749641579,
                            Volume = 12110337907L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btc.png"
                        },
                        new
                        {
                            Uid = "f8344790-2bfe-4f7d-8d18-78629252f899",
                            Age = "2814",
                            AllTimeHighUSD = 4861L,
                            Cap = 245902442713L,
                            Code = "ETH",
                            Name = "Ethereum",
                            Rank = 2L,
                            Rate = 2009.4359257497333,
                            Volume = 11770158389L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eth.png"
                        },
                        new
                        {
                            Uid = "cd70c475-9025-4202-a3b3-c667a128ef90",
                            Age = "3208",
                            AllTimeHighUSD = 1L,
                            Cap = 80650366506L,
                            Code = "USDT",
                            Name = "Tether",
                            Rank = 3L,
                            Rate = 1.0008881832810113,
                            Volume = 29981592764L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdt.png"
                        },
                        new
                        {
                            Uid = "8bf5cc93-6db8-4ed1-9afb-e9ba73598937",
                            Age = "2112",
                            AllTimeHighUSD = 692L,
                            Cap = 51303060046L,
                            Code = "BNB",
                            Name = "BNB",
                            Rank = 4L,
                            Rate = 326.31460014781129,
                            Volume = 601475322L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bnb.png"
                        },
                        new
                        {
                            Uid = "e63acbec-3dc7-4568-ac14-30b4adb729fc",
                            Age = "1647",
                            AllTimeHighUSD = 1L,
                            Cap = 31890674516L,
                            Code = "USDC",
                            Name = "USD Coin",
                            Rank = 5L,
                            Rate = 0.99906956237183553,
                            Volume = 2131442649L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdc.png"
                        },
                        new
                        {
                            Uid = "873576e0-90ad-423c-8bb8-3a13c57b7361",
                            Age = "4120",
                            AllTimeHighUSD = 4L,
                            Cap = 26621449102L,
                            Code = "XRP",
                            Name = "XRP",
                            Rank = 6L,
                            Rate = 0.51441608174902442,
                            Volume = 924923532L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xrp.png"
                        },
                        new
                        {
                            Uid = "9659bfe1-6980-45ea-8eac-8674925120aa",
                            Age = "2019",
                            AllTimeHighUSD = 3L,
                            Cap = 14892005010L,
                            Code = "ADA",
                            Name = "Cardano",
                            Rank = 7L,
                            Rate = 0.42493925406676497,
                            Volume = 400520948L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ada.png"
                        },
                        new
                        {
                            Uid = "96fc943f-9456-4fbb-95a0-905c5395ecb5",
                            Age = "3405",
                            AllTimeHighUSD = 1L,
                            Cap = 11522625745L,
                            Code = "DOGE",
                            Name = "Dogecoin",
                            Rank = 8L,
                            Rate = 0.086851280356138386,
                            Volume = 580249613L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/doge.png"
                        },
                        new
                        {
                            Uid = "df7c27ba-397d-48ab-bcaf-4266a8bfae66",
                            Age = "1443",
                            AllTimeHighUSD = 59L,
                            Cap = 10454208201L,
                            Code = "OKB",
                            Name = "OKB",
                            Rank = 9L,
                            Rate = 43.296753238680481,
                            Volume = 10300220L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/okb.png"
                        },
                        new
                        {
                            Uid = "20342bf1-21fe-4b6a-8855-6f6836cce96e",
                            Age = "1445",
                            AllTimeHighUSD = 3L,
                            Cap = 10422239560L,
                            Code = "MATIC",
                            Name = "Polygon",
                            Rank = 10L,
                            Rate = 1.1304598432321304,
                            Volume = 277086510L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/matic.png"
                        },
                        new
                        {
                            Uid = "ad600520-465d-4196-9c3b-896452d5ff31",
                            Age = "1096",
                            AllTimeHighUSD = 260L,
                            Cap = 9643105628L,
                            Code = "SOL",
                            Name = "Solana",
                            Rank = 11L,
                            Rate = 24.622276579457843,
                            Volume = 599873521L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sol.png"
                        },
                        new
                        {
                            Uid = "8ae4b52c-ef14-417b-bb83-f5cfe1662541",
                            Age = "1933",
                            AllTimeHighUSD = 1L,
                            Cap = 9349403278L,
                            Code = "DAI",
                            Name = "Dai",
                            Rank = 12L,
                            Rate = 0.99896975301912971,
                            Volume = 145345881L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dai.png"
                        },
                        new
                        {
                            Uid = "f86b5501-149a-43c3-a409-caae71563849",
                            Age = "963",
                            AllTimeHighUSD = 55L,
                            Cap = 7216234937L,
                            Code = "DOT",
                            Name = "Polkadot",
                            Rank = 13L,
                            Rate = 6.5941059350564526,
                            Volume = 196136715L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dot.png"
                        },
                        new
                        {
                            Uid = "be46aad2-de68-4eda-8726-6c7dc58bc7a4",
                            Age = "4205",
                            AllTimeHighUSD = 413L,
                            Cap = 6867505577L,
                            Code = "LTC",
                            Name = "Litecoin",
                            Rank = 14L,
                            Rate = 94.466823379278523,
                            Volume = 506762508L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ltc.png"
                        },
                        new
                        {
                            Uid = "1a12cfa4-3e0c-4291-b822-272c0db9e4e9",
                            Age = "1301",
                            AllTimeHighUSD = 1L,
                            Cap = 6753399417L,
                            Code = "BUSD",
                            Name = "Binance USD",
                            Rank = 15L,
                            Rate = 1.0019091540080731,
                            Volume = 2131249600L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/busd.png"
                        },
                        new
                        {
                            Uid = "227b2e47-628f-4fd8-b112-2f14a8f7913f",
                            Age = "799",
                            AllTimeHighUSD = 0L,
                            Cap = 6529338418L,
                            Code = "SHIB",
                            Name = "Shiba Inu",
                            Rank = 16L,
                            Rate = 1.1079815049231357E-05,
                            Volume = 177337714L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/shib.png"
                        },
                        new
                        {
                            Uid = "3d6495c1-0a6a-44f5-ae71-23c5a9d10dc7",
                            Age = "933",
                            AllTimeHighUSD = 146L,
                            Cap = 6153496756L,
                            Code = "AVAX",
                            Name = "Avalanche",
                            Rank = 17L,
                            Rate = 18.864857950030537,
                            Volume = 273147965L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/avax.png"
                        },
                        new
                        {
                            Uid = "b32d3494-0e2e-4e8f-90a1-a74654d0cd90",
                            Age = "2038",
                            AllTimeHighUSD = 0L,
                            Cap = 6025817589L,
                            Code = "TRX",
                            Name = "TRON",
                            Rank = 18L,
                            Rate = 0.066335058912063344,
                            Volume = 181564796L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/trx.png"
                        },
                        new
                        {
                            Uid = "7f3184aa-6784-490b-9b55-586c446466e6",
                            Age = "21",
                            AllTimeHighUSD = 12L,
                            Cap = 5445384888L,
                            Code = "ARB",
                            Name = "Arbitrum",
                            Rank = 19L,
                            Rate = 1.3548179589002987,
                            Volume = 1046271860L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/arb.png"
                        },
                        new
                        {
                            Uid = "07882747-08f7-45c9-b185-d2b5cc07eebd",
                            Age = "2035",
                            AllTimeHighUSD = 53L,
                            Cap = 3847806271L,
                            Code = "LINK",
                            Name = "Chainlink",
                            Rank = 20L,
                            Rate = 7.4411264640052144,
                            Volume = 213379211L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/link.png"
                        },
                        new
                        {
                            Uid = "954ab37d-6470-451a-87e9-1286f06f2b2f",
                            Age = "1532",
                            AllTimeHighUSD = 69231L,
                            Cap = 3594285291L,
                            Code = "WBTC",
                            Name = "Wrapped Bitcoin",
                            Rank = 21L,
                            Rate = 30387.424050003468,
                            Volume = 210801018L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/wbtc.png"
                        },
                        new
                        {
                            Uid = "5b6f9c59-6e3d-4b5a-aa84-e0b45cedc926",
                            Age = "2453",
                            AllTimeHighUSD = 169L,
                            Cap = 3128581467L,
                            Code = "ETC",
                            Name = "Ethereum Classic",
                            Rank = 22L,
                            Rate = 22.275222847304718,
                            Volume = 199755588L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/etc.png"
                        },
                        new
                        {
                            Uid = "5480de55-8576-4077-ae04-7bb0c2e19754",
                            Age = "3282",
                            AllTimeHighUSD = 517L,
                            Cap = 2966640940L,
                            Code = "XMR",
                            Name = "Monero",
                            Rank = 23L,
                            Rate = 162.41889788396699,
                            Volume = 70093418L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xmr.png"
                        },
                        new
                        {
                            Uid = "ca69d6d1-a161-447c-ab7b-3b01e883faa5",
                            Age = "938",
                            AllTimeHighUSD = 45L,
                            Cap = 2925381898L,
                            Code = "UNI",
                            Name = "Uniswap",
                            Rank = 24L,
                            Rate = 6.195608698729786,
                            Volume = 99949699L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/uni.png"
                        },
                        new
                        {
                            Uid = "996deb32-b17c-4212-a07f-8cbd6758d2db",
                            Age = "2376",
                            AllTimeHighUSD = 44L,
                            Cap = 2818399814L,
                            Code = "ATOM",
                            Name = "Cosmos",
                            Rank = 25L,
                            Rate = 11.815959899295345,
                            Volume = 127011892L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/atom.png"
                        },
                        new
                        {
                            Uid = "5ed6d1d4-4663-4dd8-a81a-59e9e000a98f",
                            Age = "3172",
                            AllTimeHighUSD = 1L,
                            Cap = 2803651541L,
                            Code = "XLM",
                            Name = "Stellar",
                            Rank = 26L,
                            Rate = 0.1048605169525406,
                            Volume = 51728530L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xlm.png"
                        },
                        new
                        {
                            Uid = "ea687a12-4444-4a54-9135-758491cb567e",
                            Age = "2081",
                            AllTimeHighUSD = 4356L,
                            Cap = 2650155454L,
                            Code = "BCH",
                            Name = "Bitcoin Cash",
                            Rank = 27L,
                            Rate = 136.86199605416891,
                            Volume = 70687185L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bch.png"
                        },
                        new
                        {
                            Uid = "05c907a4-deb0-4b27-a189-250fca78c530",
                            Age = "909",
                            AllTimeHighUSD = 238L,
                            Cap = 2510872731L,
                            Code = "FIL",
                            Name = "Filecoin",
                            Rank = 28L,
                            Rate = 6.0535867293097585,
                            Volume = 132878881L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/fil.png"
                        },
                        new
                        {
                            Uid = "123bd1b6-1d5f-4759-88ca-87f97be26f34",
                            Age = "975",
                            AllTimeHighUSD = 14L,
                            Cap = 2194180620L,
                            Code = "SRM",
                            Name = "Serum",
                            Rank = 29L,
                            Rate = 0.21594670202632751,
                            Volume = 57598923L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/srm.png"
                        },
                        new
                        {
                            Uid = "6a6120b8-dd12-49db-9122-e8d0e352a702",
                            Age = "827",
                            AllTimeHighUSD = 7L,
                            Cap = 2091528832L,
                            Code = "LDO",
                            Name = "Lido DAO",
                            Rank = 30L,
                            Rate = 2.4161572053155989,
                            Volume = 123572048L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ldo.png"
                        },
                        new
                        {
                            Uid = "ca5b3024-be73-4a71-9f04-7092f1da686b",
                            Age = "1291",
                            AllTimeHighUSD = 1L,
                            Cap = 2031619214L,
                            Code = "HBAR",
                            Name = "Hedera Hashgraph",
                            Rank = 31L,
                            Rate = 0.066320362634824354,
                            Volume = 42902466L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/hbar.png"
                        },
                        new
                        {
                            Uid = "216736bf-56c3-4813-b61d-8f284f4adfe3",
                            Age = "900",
                            AllTimeHighUSD = 20L,
                            Cap = 1941871015L,
                            Code = "NEAR",
                            Name = "NEAR Protocol",
                            Rank = 32L,
                            Rate = 2.1966128181102982,
                            Volume = 176283114L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/near.png"
                        },
                        new
                        {
                            Uid = "98b848eb-bacb-4472-aba6-7a1fdc6cd460",
                            Age = "2060",
                            AllTimeHighUSD = 0L,
                            Cap = 1835849605L,
                            Code = "VET",
                            Name = "VeChain",
                            Rank = 33L,
                            Rate = 0.025318171012815527,
                            Volume = 41907992L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/vet.png"
                        },
                        new
                        {
                            Uid = "c357517c-9cca-41de-9ac2-c74436f5f834",
                            Age = "1492",
                            AllTimeHighUSD = 1L,
                            Cap = 1742687263L,
                            Code = "CRO",
                            Name = "Cronos",
                            Rank = 34L,
                            Rate = 0.068981764580794316,
                            Volume = 7649509L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cro.png"
                        },
                        new
                        {
                            Uid = "3933792c-0eae-46f3-8c3a-a2b23019ca95",
                            Age = "392",
                            AllTimeHighUSD = 27L,
                            Cap = 1651519237L,
                            Code = "APE",
                            Name = "ApeCoin",
                            Rank = 35L,
                            Rate = 4.4805947930215595,
                            Volume = 197598811L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ape.png"
                        },
                        new
                        {
                            Uid = "5143ec1f-c058-4f46-afd5-ba6a9a2c552c",
                            Age = "702",
                            AllTimeHighUSD = 495L,
                            Cap = 1650816962L,
                            Code = "ICP",
                            Name = "Internet Computer",
                            Rank = 36L,
                            Rate = 5.4603279459398069,
                            Volume = 44688712L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/icp.png"
                        },
                        new
                        {
                            Uid = "2d0457ba-a1ea-4195-bbf0-09fdff34864e",
                            Age = "176",
                            AllTimeHighUSD = 20L,
                            Cap = 1594170040L,
                            Code = "APT",
                            Name = "Aptos",
                            Rank = 37L,
                            Rate = 12.262846463104303,
                            Volume = 310152845L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/apt.png"
                        },
                        new
                        {
                            Uid = "7dc66db9-8bc4-4220-af50-585749f26159",
                            Age = "1391",
                            AllTimeHighUSD = 3L,
                            Cap = 1575340028L,
                            Code = "ALGO",
                            Name = "Algorand",
                            Rank = 38L,
                            Rate = 0.21861473534216658,
                            Volume = 59994706L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/algo.png"
                        },
                        new
                        {
                            Uid = "e04f5d05-f762-4944-9217-514938afb000",
                            Age = "524",
                            AllTimeHighUSD = 9L,
                            Cap = 1548206265L,
                            Code = "_IMX",
                            Name = "Immutable X",
                            Rank = 39L,
                            Rate = 1.1334500380214361,
                            Volume = 59935349L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_imx.png"
                        },
                        new
                        {
                            Uid = "dd335fa4-4a98-48ce-aab9-2b2289c2eb71",
                            Age = "1706",
                            AllTimeHighUSD = 427L,
                            Cap = 1497475701L,
                            Code = "QNT",
                            Name = "Quant",
                            Rank = 40L,
                            Rate = 124.03778671920671,
                            Volume = 22989970L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/qnt.png"
                        },
                        new
                        {
                            Uid = "92e50369-cecd-458f-a4cd-517e86406eb5",
                            Age = "2111",
                            AllTimeHighUSD = 24L,
                            Cap = 1394057151L,
                            Code = "EOS",
                            Name = "EOS",
                            Rank = 41L,
                            Rate = 1.2654443359627325,
                            Volume = 164795547L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eos.png"
                        },
                        new
                        {
                            Uid = "b843a92d-f6dd-48a2-ab1c-0ec41b9d78f5",
                            Age = "2034",
                            AllTimeHighUSD = 6L,
                            Cap = 1349697366L,
                            Code = "MANA",
                            Name = "Decentraland",
                            Rank = 42L,
                            Rate = 0.61540675203591522,
                            Volume = 100343643L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mana.png"
                        },
                        new
                        {
                            Uid = "11efb5c3-3ceb-4afe-84fe-7b3d4501ae81",
                            Age = "847",
                            AllTimeHighUSD = 3L,
                            Cap = 1327911676L,
                            Code = "GRT",
                            Name = "The Graph",
                            Rank = 43L,
                            Rate = 0.15024820642818762,
                            Volume = 63528779L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/grt.png"
                        },
                        new
                        {
                            Uid = "75437215-20c9-4fce-9e9d-14ca75579ac9",
                            Age = "1626",
                            AllTimeHighUSD = 3L,
                            Cap = 1297548084L,
                            Code = "FTM",
                            Name = "Fantom",
                            Rank = 44L,
                            Rate = 0.51061396968355321,
                            Volume = 312600111L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ftm.png"
                        },
                        new
                        {
                            Uid = "5d13c27c-15fc-4bd7-b659-a5bd61328b86",
                            Age = "889",
                            AllTimeHighUSD = 165L,
                            Cap = 1286469629L,
                            Code = "AXS",
                            Name = "Axie Infinity",
                            Rank = 45L,
                            Rate = 8.7608934428342931,
                            Volume = 51937698L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/axs.png"
                        },
                        new
                        {
                            Uid = "fbe620f3-cd1a-4add-a90e-6c5db8dc13a4",
                            Age = "970",
                            AllTimeHighUSD = 8L,
                            Cap = 1213382309L,
                            Code = "SAND",
                            Name = "The Sandbox",
                            Rank = 46L,
                            Rate = 0.6665903180573155,
                            Volume = 116041705L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sand.png"
                        },
                        new
                        {
                            Uid = "1dada382-fc31-43f6-9873-a759b408c2ff",
                            Age = "1198",
                            AllTimeHighUSD = 3L,
                            Cap = 1204098652L,
                            Code = "_STX",
                            Name = "Stacks",
                            Rank = 47L,
                            Rate = 0.87687742582793438,
                            Volume = 121602900L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_stx.png"
                        },
                        new
                        {
                            Uid = "426d4b9a-9d8d-4883-9589-80ed5dddace0",
                            Age = "911",
                            AllTimeHighUSD = 663L,
                            Cap = 1160144987L,
                            Code = "AAVE",
                            Name = "Aave",
                            Rank = 48L,
                            Rate = 80.770928125200655,
                            Volume = 90749892L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/aave.png"
                        },
                        new
                        {
                            Uid = "bb845e83-ef50-48fc-a3e7-7d079e218552",
                            Age = "1912",
                            AllTimeHighUSD = 16L,
                            Cap = 1074858108L,
                            Code = "THETA",
                            Name = "Theta Network",
                            Rank = 49L,
                            Rate = 1.0748581079631161,
                            Volume = 20049268L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/theta.png"
                        },
                        new
                        {
                            Uid = "69bb41d9-3c41-4cfb-81d8-8bf4ff5e1b78",
                            Age = "804",
                            AllTimeHighUSD = 42L,
                            Cap = 1056339832L,
                            Code = "FLOW",
                            Name = "Flow",
                            Rank = 50L,
                            Rate = 1.0194362398508712,
                            Volume = 23890678L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/flow.png"
                        },
                        new
                        {
                            Uid = "c01206d0-1b99-4d25-93a3-8818071705e1",
                            Age = "1839",
                            AllTimeHighUSD = 9L,
                            Cap = 1044099181L,
                            Code = "XTZ",
                            Name = "Tezos",
                            Rank = 51L,
                            Rate = 1.117674002603652,
                            Volume = 13413660L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xtz.png"
                        },
                        new
                        {
                            Uid = "c239b40d-2e60-4378-a851-660614315786",
                            Age = "951",
                            AllTimeHighUSD = 548L,
                            Cap = 1036526264L,
                            Code = "EGLD",
                            Name = "MultiversX",
                            Rank = 52L,
                            Rate = 41.016003940720196,
                            Volume = 20727486L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/egld.png"
                        },
                        new
                        {
                            Uid = "abb663c3-3469-49fa-8a10-36005de13815",
                            Age = "767",
                            AllTimeHighUSD = 4L,
                            Cap = 971061789L,
                            Code = "MX",
                            Name = "MX Token",
                            Rank = 53L,
                            Rate = 2.2210928294677328,
                            Volume = 11230083L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mx.png"
                        },
                        new
                        {
                            Uid = "038a0444-d0b5-40e2-b4fb-9a14378e1877",
                            Age = "590",
                            AllTimeHighUSD = 3L,
                            Cap = 950876060L,
                            Code = "__BIT",
                            Name = "BITDAO",
                            Rank = 54L,
                            Rate = 0.52140798636966734,
                            Volume = 4058412L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/__bit.png"
                        },
                        new
                        {
                            Uid = "35636325-f16d-45c8-b8b5-50e86ba964e4",
                            Age = "1658",
                            AllTimeHighUSD = 1L,
                            Cap = 928656143L,
                            Code = "USDP",
                            Name = "Pax Dollar",
                            Rank = 55L,
                            Rate = 0.99880958981750056,
                            Volume = 423611L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdp.png"
                        },
                        new
                        {
                            Uid = "b277c939-92f5-472c-a088-72cdab86afbe",
                            Age = "842",
                            AllTimeHighUSD = 2L,
                            Cap = 912592048L,
                            Code = "FRAX",
                            Name = "Frax",
                            Rank = 56L,
                            Rate = 0.99870729767877375,
                            Volume = 4632040L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/frax.png"
                        },
                        new
                        {
                            Uid = "798b0b2e-a312-41c4-9b26-0a51765c4220",
                            Age = "2406",
                            AllTimeHighUSD = 196L,
                            Cap = 892570611L,
                            Code = "NEO",
                            Name = "NEO",
                            Rank = 57L,
                            Rate = 12.36252589362473,
                            Volume = 30596279L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/neo.png"
                        },
                        new
                        {
                            Uid = "7a598784-823a-4e6c-a3cd-3a769f62176d",
                            Age = "1198",
                            AllTimeHighUSD = 62L,
                            Cap = 880725615L,
                            Code = "RPL",
                            Name = "Rocket Pool",
                            Rank = 58L,
                            Rate = 46.078929767765544,
                            Volume = 15099734L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rpl.png"
                        },
                        new
                        {
                            Uid = "9578a4ed-070b-48f8-bb29-2dd3558d180b",
                            Age = "1864",
                            AllTimeHighUSD = 2L,
                            Cap = 855538288L,
                            Code = "TUSD",
                            Name = "True USD",
                            Rank = 59L,
                            Rate = 0.99974566674995036,
                            Volume = 56647944L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/tusd.png"
                        },
                        new
                        {
                            Uid = "98071af9-357a-4a9a-9c8f-57a8aaff6367",
                            Age = "1028",
                            AllTimeHighUSD = 9L,
                            Cap = 843087392L,
                            Code = "RNDR",
                            Name = "Render Token",
                            Rank = 60L,
                            Rate = 1.5876871134321542,
                            Volume = 87863143L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rndr.png"
                        },
                        new
                        {
                            Uid = "b0159e95-53e2-421f-b470-21f2f8dcfb8b",
                            Age = "1586",
                            AllTimeHighUSD = 29L,
                            Cap = 831268461L,
                            Code = "SNX",
                            Name = "Synthetix",
                            Rank = 61L,
                            Rate = 2.6283183340026004,
                            Volume = 48403838L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/snx.png"
                        },
                        new
                        {
                            Uid = "810be481-3c1e-4442-a93d-0fbf0cb0d178",
                            Age = "2276",
                            AllTimeHighUSD = 119L,
                            Cap = 828116098L,
                            Code = "LUNC",
                            Name = "Luna Classic",
                            Rank = 62L,
                            Rate = 0.00012669284582174738,
                            Volume = 60224966L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/lunc.png"
                        },
                        new
                        {
                            Uid = "2c7d4693-6d95-49f0-8780-3c847c2c6cdf",
                            Age = "970",
                            AllTimeHighUSD = 7L,
                            Cap = 825120005L,
                            Code = "CRV",
                            Name = "Curve DAO Token",
                            Rank = 63L,
                            Rate = 1.0631347154224129,
                            Volume = 50675677L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/crv.png"
                        },
                        new
                        {
                            Uid = "d9dc8780-eeab-41ad-8655-8254eee33d1b",
                            Age = "884",
                            AllTimeHighUSD = 2L,
                            Cap = 813159667L,
                            Code = "CFX",
                            Name = "Conflux Token",
                            Rank = 64L,
                            Rate = 0.38767397643673057,
                            Volume = 267248994L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cfx.png"
                        },
                        new
                        {
                            Uid = "0dd40887-9493-43eb-b305-d588bb40ab22",
                            Age = "586",
                            AllTimeHighUSD = 1L,
                            Cap = 803419209L,
                            Code = "XRD",
                            Name = "Radix Native Token",
                            Rank = 65L,
                            Rate = 0.079177929219493154,
                            Volume = 16144664L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xrd.png"
                        },
                        new
                        {
                            Uid = "9f4110c1-8912-4428-9256-6e7a251609b1",
                            Age = "742",
                            AllTimeHighUSD = 4L,
                            Cap = 780230689L,
                            Code = "_KLAY",
                            Name = "Klaytn",
                            Rank = 66L,
                            Rate = 0.25288983619249283,
                            Volume = 96165252L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_klay.png"
                        },
                        new
                        {
                            Uid = "74bc713d-d3d5-4275-83e4-452a43a93325",
                            Age = "1894",
                            AllTimeHighUSD = 40L,
                            Cap = 779841435L,
                            Code = "HT",
                            Name = "Huobi Token",
                            Rank = 67L,
                            Rate = 3.8257985724268013,
                            Volume = 16402020L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ht.png"
                        },
                        new
                        {
                            Uid = "656bfb89-b9a8-4622-abdf-885116c2530f",
                            Age = "941",
                            AllTimeHighUSD = 13L,
                            Cap = 774577600L,
                            Code = "GT",
                            Name = "Gatechain Token",
                            Rank = 68L,
                            Rate = 5.4945079961524126,
                            Volume = 508581L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/gt.png"
                        },
                        new
                        {
                            Uid = "2623f19b-61f8-4b8f-92d5-2853ea9d3bb1",
                            Age = "2264",
                            AllTimeHighUSD = 6299L,
                            Cap = 730593589L,
                            Code = "MKR",
                            Name = "Maker",
                            Rank = 69L,
                            Rate = 747.31017008504386,
                            Volume = 32172507L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mkr.png"
                        },
                        new
                        {
                            Uid = "8c31e2b4-20bb-4ce8-96b0-33b256c8f969",
                            AllTimeHighUSD = 15L,
                            Cap = 730176154L,
                            Code = "WBT",
                            Name = "WhiteBIT Token",
                            Rank = 70L,
                            Rate = 4.8137561350336462,
                            Volume = 2385277L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/wbt.png"
                        },
                        new
                        {
                            Uid = "53a5caf4-79db-4faf-af7b-5d1e47252e11",
                            Age = "2356",
                            AllTimeHighUSD = 2218L,
                            Cap = 728613411L,
                            Code = "ZEC",
                            Name = "Zcash",
                            Rank = 71L,
                            Rate = 44.622822872541775,
                            Volume = 67990465L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/zec.png"
                        },
                        new
                        {
                            Uid = "93733212-4904-4c6e-b418-8821b0260adf",
                            Age = "345",
                            AllTimeHighUSD = 1L,
                            Cap = 718573479L,
                            Code = "USDD",
                            Name = "Decentralized USD",
                            Rank = 72L,
                            Rate = 0.99068212104553866,
                            Volume = 19909392L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdd.png"
                        },
                        new
                        {
                            Uid = "198b6cfa-c0fc-450e-ad0e-63f82c356b5d",
                            Age = "1610",
                            AllTimeHighUSD = 491L,
                            Cap = 700363684L,
                            Code = "BSV",
                            Name = "Bitcoin SV",
                            Rank = 73L,
                            Rate = 36.352170713002614,
                            Volume = 13024930L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bsv.png"
                        },
                        new
                        {
                            Uid = "206b78c6-f0f8-4ccc-b7f0-38df759213c5",
                            Age = "1372",
                            AllTimeHighUSD = 1L,
                            Cap = 699581929L,
                            Code = "CHZ",
                            Name = "Chiliz",
                            Rank = 74L,
                            Rate = 0.13090821005850312,
                            Volume = 79719095L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/chz.png"
                        },
                        new
                        {
                            Uid = "239dc9ae-c859-4f3c-98e9-4ec3c2ffacd5",
                            Age = "727",
                            AllTimeHighUSD = 188L,
                            Cap = 694182713L,
                            Code = "MINA",
                            Name = "Mina Protocol",
                            Rank = 75L,
                            Rate = 0.78559999246932066,
                            Volume = 48803309L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mina.png"
                        },
                        new
                        {
                            Uid = "2d499fcf-0a52-4a59-8a1d-386421dbde88",
                            Age = "916",
                            AllTimeHighUSD = 44L,
                            Cap = 677474395L,
                            Code = "CAKE",
                            Name = "PancakeSwap",
                            Rank = 76L,
                            Rate = 3.6559057060612723,
                            Volume = 52025532L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cake.png"
                        },
                        new
                        {
                            Uid = "fcf1825a-b59a-45a3-a709-165f63edaa9d",
                            Age = "1996",
                            AllTimeHighUSD = 28L,
                            Cap = 668334731L,
                            Code = "KCS",
                            Name = "KuCoin Shares",
                            Rank = 77L,
                            Rate = 8.8355279000857276,
                            Volume = 1364003L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kcs.png"
                        },
                        new
                        {
                            Uid = "df51cae1-e394-4205-9a6b-a7121b6d7071",
                            Age = "1189",
                            AllTimeHighUSD = 0L,
                            Cap = 665049722L,
                            Code = "_SURE",
                            Name = "inSure",
                            Rank = 78L,
                            Rate = 0.0076776003523308248,
                            Volume = 3034637L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_sure.png"
                        },
                        new
                        {
                            Uid = "7273f03d-d0f2-4a6e-9214-1e37e300c5e6",
                            Age = "3344",
                            AllTimeHighUSD = 1642L,
                            Cap = 651136662L,
                            Code = "DASH",
                            Name = "Dash",
                            Rank = 79L,
                            Rate = 57.983550702574263,
                            Volume = 65698320L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dash.png"
                        },
                        new
                        {
                            Uid = "b843440f-4d60-42a3-aaaf-4e146f386ab4",
                            Age = "563",
                            AllTimeHighUSD = 86L,
                            Cap = 647976770L,
                            Code = "__GMX",
                            Name = "GMX",
                            Rank = 80L,
                            Rate = 81.073507988673299,
                            Volume = 38651507L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/__gmx.png"
                        },
                        new
                        {
                            Uid = "97193e12-2d24-4972-8833-0abbb4fcaaec",
                            Age = "842",
                            AllTimeHighUSD = 45L,
                            Cap = 646351012L,
                            Code = "FXS",
                            Name = "Frax Share",
                            Rank = 81L,
                            Rate = 9.0715358525988101,
                            Volume = 24544289L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/fxs.png"
                        },
                        new
                        {
                            Uid = "1bf1939f-82c7-4646-99b8-dee16e222eb4",
                            Age = "2129",
                            AllTimeHighUSD = 6L,
                            Cap = 617694856L,
                            Code = "MIOTA",
                            Name = "IOTA",
                            Rank = 82L,
                            Rate = 0.22222994285848705,
                            Volume = 5754165L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/miota.png"
                        },
                        new
                        {
                            Uid = "ab943b1c-d2d1-4018-8157-06298228b5fe",
                            Age = "650",
                            AllTimeHighUSD = 0L,
                            Cap = 615081473L,
                            Code = "XEC",
                            Name = "eCash",
                            Rank = 83L,
                            Rate = 3.1770908082477563E-05,
                            Volume = 4034928L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xec.png"
                        },
                        new
                        {
                            Uid = "7fcd41e9-be52-4db1-b901-c9ce6f2db390",
                            Age = "1838",
                            AllTimeHighUSD = 0L,
                            Cap = 592646573L,
                            Code = "XDC",
                            Name = "XDC Network",
                            Rank = 84L,
                            Rate = 0.042856757030258409,
                            Volume = 3944111L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xdc.png"
                        },
                        new
                        {
                            Uid = "c1e9a6a0-259c-4df1-a7b8-0a23127922b9",
                            Age = "1532",
                            AllTimeHighUSD = 0L,
                            Cap = 588833375L,
                            Code = "BTT",
                            Name = "BitTorrent",
                            Rank = 85L,
                            Rate = 6.1889839871637984E-07,
                            Volume = 9281947L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btt.png"
                        },
                        new
                        {
                            Uid = "bca4932e-101a-4ed0-9d3a-eb97623a3584",
                            Age = "322",
                            AllTimeHighUSD = 0L,
                            Cap = 583907727L,
                            Code = "KAS",
                            Name = "Kaspa",
                            Rank = 86L,
                            Rate = 0.032612547915839396,
                            Volume = 18569847L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kas.png"
                        },
                        new
                        {
                            Uid = "10053db6-f624-4e45-a6a9-599de8a7a494",
                            Age = "1359",
                            AllTimeHighUSD = 21L,
                            Cap = 549835701L,
                            Code = "RUNE",
                            Name = "THORChain",
                            Rank = 87L,
                            Rate = 1.6321258352499231,
                            Volume = 31640143L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rune.png"
                        },
                        new
                        {
                            Uid = "7e5cb3b0-25ca-43c3-b2e5-25d37dbc812e",
                            Age = "903",
                            AllTimeHighUSD = 25L,
                            Cap = 537776849L,
                            Code = "INJ",
                            Name = "Injective Protocol",
                            Rank = 88L,
                            Rate = 6.7217437819127657,
                            Volume = 107047190L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/inj.png"
                        },
                        new
                        {
                            Uid = "882a48bc-c924-47b7-8f4a-00863f4446f4",
                            Age = "675",
                            AllTimeHighUSD = 0L,
                            Cap = 537254667L,
                            Code = "BABYDOGE",
                            Name = "Baby Doge Coin",
                            Rank = 89L,
                            Rate = 2.4980008270697834E-09,
                            Volume = 10275593L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/babydoge.png"
                        },
                        new
                        {
                            Uid = "f00c1b45-b77f-4db5-b732-64626535ed8e",
                            Age = "520",
                            AllTimeHighUSD = 84L,
                            Cap = 532259706L,
                            Code = "ENS",
                            Name = "Ethereum Name Service",
                            Rank = 90L,
                            Rate = 13.590619143368228,
                            Volume = 27588209L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ens.png"
                        },
                        new
                        {
                            Uid = "0792e903-0555-4934-afac-40ea40ff4fbe",
                            Age = "1295",
                            AllTimeHighUSD = 2222L,
                            Cap = 527549554L,
                            Code = "PAXG",
                            Name = "PAX Gold",
                            Rank = 91L,
                            Rate = 2042.9919540285246,
                            Volume = 14703777L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/paxg.png"
                        },
                        new
                        {
                            Uid = "d695a145-a009-433b-900c-c1e1314c00b0",
                            Age = "316",
                            AllTimeHighUSD = 3L,
                            Cap = 523108103L,
                            Code = "OP",
                            Name = "Optimism",
                            Rank = 92L,
                            Rate = 2.4359119352872192,
                            Volume = 169354388L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/op.png"
                        },
                        new
                        {
                            Uid = "f94d3800-f404-46dc-88f6-dbd9ebe9cda8",
                            Age = "675",
                            AllTimeHighUSD = 1L,
                            Cap = 486891673L,
                            Code = "AGIX",
                            Name = "SingularityNET",
                            Rank = 93L,
                            Rate = 0.40368364922792982,
                            Volume = 65325438L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/agix.png"
                        },
                        new
                        {
                            Uid = "10a2238d-018e-463c-acda-a0da7b8c2f8b",
                            Age = "2051",
                            AllTimeHighUSD = 4L,
                            Cap = 484033579L,
                            Code = "LRC",
                            Name = "Loopring",
                            Rank = 94L,
                            Rate = 0.36153227169751667,
                            Volume = 26078150L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/lrc.png"
                        },
                        new
                        {
                            Uid = "4968bddf-4553-41b1-9b86-be185f98da7f",
                            Age = "706",
                            AllTimeHighUSD = 40L,
                            Cap = 483242748L,
                            Code = "CSPR",
                            Name = "Casper Network",
                            Rank = 95L,
                            Rate = 0.044268223688168698,
                            Volume = 7331958L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cspr.png"
                        },
                        new
                        {
                            Uid = "1d2ccb4a-4daa-4a0c-a3f9-fe372a8228aa",
                            Age = "618",
                            AllTimeHighUSD = 11L,
                            Cap = 454317232L,
                            Code = "OSMO",
                            Name = "Osmosis",
                            Rank = 96L,
                            Rate = 0.80657164263503145,
                            Volume = 10831520L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/osmo.png"
                        },
                        new
                        {
                            Uid = "347040da-120d-41c7-8fd5-6a46bdb077d0",
                            Age = "1419",
                            AllTimeHighUSD = 0L,
                            Cap = 451724888L,
                            Code = "RSR",
                            Name = "Reserve Rights",
                            Rank = 97L,
                            Rate = 0.0045180395383625487,
                            Volume = 10588914L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rsr.png"
                        },
                        new
                        {
                            Uid = "54e83eba-bbbe-4675-bec6-590b928e6c86",
                            Age = "1198",
                            AllTimeHighUSD = 9L,
                            Cap = 450724496L,
                            Code = "KAVA",
                            Name = "Kava",
                            Rank = 98L,
                            Rate = 0.94235684969696731,
                            Volume = 16450427L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kava.png"
                        },
                        new
                        {
                            Uid = "c5229aa4-3105-4925-9905-5d6de05b727f",
                            Age = "839",
                            AllTimeHighUSD = 9L,
                            Cap = 443724164L,
                            Code = "1INCH",
                            Name = "1inch",
                            Rank = 99L,
                            Rate = 0.54478528873423893,
                            Volume = 25365079L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/1inch.png"
                        },
                        new
                        {
                            Uid = "04dd475d-ce79-4ad9-afd8-82745b0c6a94",
                            Age = "693",
                            AllTimeHighUSD = 60L,
                            Cap = 443590805L,
                            Code = "CVX",
                            Name = "Convex Finance",
                            Rank = 100L,
                            Rate = 5.8113251636007464,
                            Volume = 10949452L,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cvx.png"
                        });
                });

            modelBuilder.Entity("InvestmentApp.API.Models.SiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f4417f7f-969e-4665-8ede-c5cf6186d494",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59b33f55-c672-40d6-9dd0-ff67e00d4991",
                            Email = "admin@admin.adm",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEJc7hM2CaGiFFD7KgE8VPnWpmAaBYyHT1Rdrl2QFivdoxrGvwF0yxeHLhCF6/rANNQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "831e82c9-37ff-4d7b-9b9e-a8b759e1b6a9",
                            TwoFactorEnabled = false,
                            UserName = "superuser"
                        });
                });

            modelBuilder.Entity("InvestmentApp.API.Models.UserCoins", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoinId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CoinCount")
                        .HasColumnType("float");

                    b.Property<string>("SiteUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "CoinId");

                    b.HasIndex("CoinId");

                    b.HasIndex("SiteUserId");

                    b.ToTable("UserCoins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "I",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InvestmentApp.API.Models.UserCoins", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany("Coins")
                        .HasForeignKey("SiteUserId");

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestmentApp.API.Models.SiteUser", b =>
                {
                    b.Navigation("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
