// <auto-generated />
using System;
using InvestmentApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentApp.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InvestmentApp.API.Models.Coin", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AllTimeHighUSD")
                        .HasColumnType("float");

                    b.Property<double>("Cap")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<string>("png64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Uid = "158ac793-4dbb-40cf-bd35-fb6d57b474af",
                            Age = "5253",
                            AllTimeHighUSD = 68781.0,
                            Cap = 0.0,
                            Code = "BTC",
                            Color = "#fa9e32",
                            Name = "Bitcoin",
                            Rank = 1,
                            Rate = 27241.641898363567,
                            Volume = 8345771558.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btc.png"
                        },
                        new
                        {
                            Uid = "f8ca17ca-9a01-4722-a7b7-743d95108e45",
                            Age = "2854",
                            AllTimeHighUSD = 4861.0,
                            Cap = 0.0,
                            Code = "ETH",
                            Color = "#282a2a",
                            Name = "Ethereum",
                            Rank = 2,
                            Rate = 1854.7672150085675,
                            Volume = 5661436349.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eth.png"
                        },
                        new
                        {
                            Uid = "8ea733fe-4cf9-4f52-8244-15f180883284",
                            Age = "3248",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "USDT",
                            Color = "#e9f4f4",
                            Name = "Tether",
                            Rank = 3,
                            Rate = 1.0014379143156151,
                            Volume = 18784650586.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdt.png"
                        },
                        new
                        {
                            Uid = "dcaf5d40-4cb0-451a-827e-9cf047e25c95",
                            Age = "2152",
                            AllTimeHighUSD = 692.0,
                            Cap = 0.0,
                            Code = "BNB",
                            Color = "#f4bc2c",
                            Name = "BNB",
                            Rank = 4,
                            Rate = 312.61771255644658,
                            Volume = 386395358.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bnb.png"
                        },
                        new
                        {
                            Uid = "62f5e13b-c30c-4292-96fb-7b6c27c24130",
                            Age = "1687",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "USDC",
                            Color = "#eef4f9",
                            Name = "USD Coin",
                            Rank = 5,
                            Rate = 1.0008820307021262,
                            Volume = 1220839797.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdc.png"
                        },
                        new
                        {
                            Uid = "eb9a2d57-3bd5-4944-a9bb-7074ead8efd4",
                            Age = "4160",
                            AllTimeHighUSD = 4.0,
                            Cap = 0.0,
                            Code = "XRP",
                            Color = "#040404",
                            Name = "XRP",
                            Rank = 6,
                            Rate = 0.46182399191241968,
                            Volume = 675516090.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xrp.png"
                        },
                        new
                        {
                            Uid = "85e0a8e8-9849-4acb-978d-fa0dcba48078",
                            Age = "2059",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "ADA",
                            Color = "#226ed8",
                            Name = "Cardano",
                            Rank = 7,
                            Rate = 0.37037443526314728,
                            Volume = 123847620.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ada.png"
                        },
                        new
                        {
                            Uid = "9e343368-f4b0-49ee-828a-a400a5cd32f2",
                            Age = "1483",
                            AllTimeHighUSD = 59.0,
                            Cap = 0.0,
                            Code = "OKB",
                            Color = "#ededed",
                            Name = "OKB",
                            Rank = 8,
                            Rate = 46.218883237170076,
                            Volume = 14684568.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/okb.png"
                        },
                        new
                        {
                            Uid = "d7844d96-e1d4-4076-91dc-8fd9b3768bb8",
                            Age = "3445",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "DOGE",
                            Color = "#eee0b6",
                            Name = "Dogecoin",
                            Rank = 9,
                            Rate = 0.072944980083112024,
                            Volume = 112633190.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/doge.png"
                        },
                        new
                        {
                            Uid = "7963f8ae-b8f5-48dc-a4eb-7850bec5ae20",
                            Age = "1973",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "DAI",
                            Color = "#fcb934",
                            Name = "Dai",
                            Rank = 10,
                            Rate = 1.0024793381072639,
                            Volume = 129341363.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dai.png"
                        },
                        new
                        {
                            Uid = "e0591ac5-d3c8-4656-aab3-8037fe700f4f",
                            Age = "1485",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "MATIC",
                            Color = "#8444e4",
                            Name = "Polygon",
                            Rank = 11,
                            Rate = 0.88484475254066264,
                            Volume = 168129638.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/matic.png"
                        },
                        new
                        {
                            Uid = "4ce1833f-4e64-4668-a903-841f280ad10c",
                            Age = "1136",
                            AllTimeHighUSD = 260.0,
                            Cap = 0.0,
                            Code = "SOL",
                            Color = "#68a1c9",
                            Name = "Solana",
                            Rank = 12,
                            Rate = 19.956291824457203,
                            Volume = 231902664.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sol.png"
                        },
                        new
                        {
                            Uid = "903228da-f2d6-465b-be5d-2a4e81b64263",
                            Age = "2078",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "TRX",
                            Color = "#c43429",
                            Name = "TRON",
                            Rank = 13,
                            Rate = 0.080506686686656712,
                            Volume = 196584924.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/trx.png"
                        },
                        new
                        {
                            Uid = "b77945b4-b945-4405-9642-ca164a713a28",
                            Age = "4245",
                            AllTimeHighUSD = 413.0,
                            Cap = 0.0,
                            Code = "LTC",
                            Color = "#345c9c",
                            Name = "Litecoin",
                            Rank = 14,
                            Rate = 91.495730883212772,
                            Volume = 395131851.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ltc.png"
                        },
                        new
                        {
                            Uid = "cfa74a2c-fb59-43d7-bd02-8116b1049c96",
                            Age = "1002",
                            AllTimeHighUSD = 55.0,
                            Cap = 0.0,
                            Code = "DOT",
                            Color = "#e4047c",
                            Name = "Polkadot",
                            Rank = 15,
                            Rate = 5.3947946470223025,
                            Volume = 97466467.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dot.png"
                        },
                        new
                        {
                            Uid = "3e5d58f2-4686-4f85-9fea-8ff17ce9ddb6",
                            Age = "1340",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "BUSD",
                            Color = "#f4bc0c",
                            Name = "Binance USD",
                            Rank = 16,
                            Rate = 1.0035128892251934,
                            Volume = 1024924027.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/busd.png"
                        },
                        new
                        {
                            Uid = "eb8b8f63-91a6-4199-aad3-5b608a82e079",
                            Age = "61",
                            AllTimeHighUSD = 12.0,
                            Cap = 0.0,
                            Code = "ARB",
                            Color = "#806418",
                            Name = "Arbitrum",
                            Rank = 17,
                            Rate = 1.1694433372849344,
                            Volume = 216134479.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/arb.png"
                        },
                        new
                        {
                            Uid = "a8185f9d-ccd8-4ed1-8686-6192769fb214",
                            Age = "839",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "SHIB",
                            Color = "#faa00d",
                            Name = "Shiba Inu",
                            Rank = 18,
                            Rate = 8.9101940185693391E-06,
                            Volume = 123797463.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/shib.png"
                        },
                        new
                        {
                            Uid = "9b8f4f7b-002b-4919-9f3d-3ca6f3db8446",
                            Age = "973",
                            AllTimeHighUSD = 146.0,
                            Cap = 0.0,
                            Code = "AVAX",
                            Color = "#eb4343",
                            Name = "Avalanche",
                            Rank = 19,
                            Rate = 14.724631235843374,
                            Volume = 78818426.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/avax.png"
                        },
                        new
                        {
                            Uid = "f956cb6f-45f3-413b-a243-17a678875c3b",
                            Age = "2075",
                            AllTimeHighUSD = 53.0,
                            Cap = 0.0,
                            Code = "LINK",
                            Color = "#2959d9",
                            Name = "Chainlink",
                            Rank = 20,
                            Rate = 6.5127578008128646,
                            Volume = 95783657.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/link.png"
                        },
                        new
                        {
                            Uid = "89e29638-0223-4121-8661-ff3441ac2cbe",
                            Age = "1572",
                            AllTimeHighUSD = 69231.0,
                            Cap = 0.0,
                            Code = "WBTC",
                            Color = "#f09444",
                            Name = "Wrapped Bitcoin",
                            Rank = 21,
                            Rate = 27277.127251493635,
                            Volume = 63165683.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/wbtc.png"
                        },
                        new
                        {
                            Uid = "39194276-d749-4201-bab5-49d53ae2cff9",
                            Age = "3322",
                            AllTimeHighUSD = 517.0,
                            Cap = 0.0,
                            Code = "XMR",
                            Color = "#fc6404",
                            Name = "Monero",
                            Rank = 22,
                            Rate = 151.47519722569675,
                            Volume = 54814257.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xmr.png"
                        },
                        new
                        {
                            Uid = "e2c83dd8-ccea-47cf-8014-1c786e3b4cf8",
                            Age = "2493",
                            AllTimeHighUSD = 169.0,
                            Cap = 0.0,
                            Code = "ETC",
                            Color = "#3ab93a",
                            Name = "Ethereum Classic",
                            Rank = 23,
                            Rate = 18.35519051645187,
                            Volume = 67624120.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/etc.png"
                        },
                        new
                        {
                            Uid = "c77f6f84-970c-4b07-8644-bf4b680815e9",
                            Age = "2416",
                            AllTimeHighUSD = 44.0,
                            Cap = 0.0,
                            Code = "ATOM",
                            Color = "#30334c",
                            Name = "Cosmos",
                            Rank = 24,
                            Rate = 10.521418807681862,
                            Volume = 50149248.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/atom.png"
                        },
                        new
                        {
                            Uid = "b09fb92a-22be-458f-88e0-5ebfa92dcf6d",
                            Age = "978",
                            AllTimeHighUSD = 45.0,
                            Cap = 0.0,
                            Code = "UNI",
                            Color = "#fc047c",
                            Name = "Uniswap",
                            Rank = 25,
                            Rate = 5.0997957044720827,
                            Volume = 50447095.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/uni.png"
                        },
                        new
                        {
                            Uid = "d6d9f3f0-48e7-4889-bec3-8a58c2d0e1d9",
                            Age = "3212",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "XLM",
                            Color = "#040404",
                            Name = "Stellar",
                            Rank = 26,
                            Rate = 0.088168461096154088,
                            Volume = 28936168.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xlm.png"
                        },
                        new
                        {
                            Uid = "107d2551-3ad5-4606-9de1-4cfc80201fef",
                            Age = "2121",
                            AllTimeHighUSD = 4356.0,
                            Cap = 0.0,
                            Code = "BCH",
                            Color = "#f1f9f7",
                            Name = "Bitcoin Cash",
                            Rank = 27,
                            Rate = 116.41798063111989,
                            Volume = 42421557.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bch.png"
                        },
                        new
                        {
                            Uid = "4233124a-a55e-4e59-a984-ad8d4377ee66",
                            Age = "742",
                            AllTimeHighUSD = 495.0,
                            Cap = 0.0,
                            Code = "ICP",
                            Color = "#ea594e",
                            Name = "Internet Computer",
                            Rank = 28,
                            Rate = 5.057155162474694,
                            Volume = 18064366.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/icp.png"
                        },
                        new
                        {
                            Uid = "72540a41-a775-46ef-a002-06c7154e88fe",
                            Age = "949",
                            AllTimeHighUSD = 238.0,
                            Cap = 0.0,
                            Code = "FIL",
                            Color = "#0492fc",
                            Name = "Filecoin",
                            Rank = 29,
                            Rate = 4.497146557077869,
                            Volume = 52255009.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/fil.png"
                        },
                        new
                        {
                            Uid = "2b7f4395-b177-4fc0-be4f-3b56d6f6aa2d",
                            Age = "867",
                            AllTimeHighUSD = 7.0,
                            Cap = 0.0,
                            Code = "LDO",
                            Color = "#f49b8a",
                            Name = "Lido DAO",
                            Rank = 30,
                            Rate = 2.0580460705219625,
                            Volume = 45265025.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ldo.png"
                        },
                        new
                        {
                            Uid = "bc686c4c-8b90-43d0-8ca4-760668daa70d",
                            Age = "1331",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "HBAR",
                            Color = "#f8f8f8",
                            Name = "Hedera Hashgraph",
                            Rank = 31,
                            Rate = 0.052718377774173479,
                            Volume = 13441544.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/hbar.png"
                        },
                        new
                        {
                            Uid = "effb591b-572b-4f3b-9388-6278d073ecd8",
                            Age = "1532",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "CRO",
                            Color = "#f6f7f8",
                            Name = "Cronos",
                            Rank = 32,
                            Rate = 0.062445970171758708,
                            Volume = 2390177.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cro.png"
                        },
                        new
                        {
                            Uid = "f1d193e6-f508-49cf-b236-dc406924fb81",
                            Age = "940",
                            AllTimeHighUSD = 20.0,
                            Cap = 0.0,
                            Code = "NEAR",
                            Color = "#040404",
                            Name = "NEAR Protocol",
                            Rank = 33,
                            Rate = 1.6458246730074639,
                            Volume = 53495918.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/near.png"
                        },
                        new
                        {
                            Uid = "b2297bfe-5ef3-455d-bd45-cb72fafc631b",
                            Age = "1068",
                            AllTimeHighUSD = 9.0,
                            Cap = 0.0,
                            Code = "RNDR",
                            Color = "#cedfe8",
                            Name = "Render Token",
                            Rank = 34,
                            Rate = 2.7357552973988675,
                            Volume = 235313580.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rndr.png"
                        },
                        new
                        {
                            Uid = "31add07b-f589-482a-b0b4-23404b6ff248",
                            Age = "2100",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "VET",
                            Color = "#6488e1",
                            Name = "VeChain",
                            Rank = 35,
                            Rate = 0.019457110111889876,
                            Volume = 23019773.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/vet.png"
                        },
                        new
                        {
                            Uid = "f37784c3-cdf9-4791-a906-66aad33c9ce2",
                            Age = "432",
                            AllTimeHighUSD = 27.0,
                            Cap = 0.0,
                            Code = "APE",
                            Color = "#ecf0f6",
                            Name = "ApeCoin",
                            Rank = 36,
                            Rate = 3.5099022646059326,
                            Volume = 43553141.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ape.png"
                        },
                        new
                        {
                            Uid = "ff6a85b3-1d97-4e1e-a371-de1c43fc29eb",
                            Age = "807",
                            AllTimeHighUSD = 4.0,
                            Cap = 0.0,
                            Code = "MX",
                            Color = "#05bb93",
                            Name = "MX Token",
                            Rank = 37,
                            Rate = 2.9461884299774215,
                            Volume = 2601343.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mx.png"
                        },
                        new
                        {
                            Uid = "323cc33f-0d14-45a6-a8c7-94256dfebd3c",
                            Age = "1746",
                            AllTimeHighUSD = 427.0,
                            Cap = 0.0,
                            Code = "QNT",
                            Color = "#ec3b1b",
                            Name = "Quant",
                            Rank = 38,
                            Rate = 102.26535229422835,
                            Volume = 12630439.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/qnt.png"
                        },
                        new
                        {
                            Uid = "73326ccf-466d-4998-874e-5ddaad2525b2",
                            Age = "1431",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "ALGO",
                            Color = "#efefef",
                            Name = "Algorand",
                            Rank = 39,
                            Rate = 0.16244455523032547,
                            Volume = 20823087.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/algo.png"
                        },
                        new
                        {
                            Uid = "7d2172e5-8fa4-443c-b1fa-e9b20646755f",
                            Age = "564",
                            AllTimeHighUSD = 9.0,
                            Cap = 0.0,
                            Code = "_IMX",
                            Color = "#13242c",
                            Name = "Immutable X",
                            Rank = 40,
                            Rate = 0.76716224833907176,
                            Volume = 23812491.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_imx.png"
                        },
                        new
                        {
                            Uid = "9e05886e-7ea3-483d-8d3b-9b1d8ed565e7",
                            Age = "216",
                            AllTimeHighUSD = 20.0,
                            Cap = 0.0,
                            Code = "APT",
                            Color = "#040404",
                            Name = "Aptos",
                            Rank = 41,
                            Rate = 8.3742437156870082,
                            Volume = 65664544.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/apt.png"
                        },
                        new
                        {
                            Uid = "651c3291-471f-4588-af47-b4273745b26b",
                            Age = "886",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "GRT",
                            Color = "#453bab",
                            Name = "The Graph",
                            Rank = 42,
                            Rate = 0.12238242736012531,
                            Volume = 24105179.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/grt.png"
                        },
                        new
                        {
                            Uid = "da045c38-1859-45c2-9ad2-dd2ec2a75481",
                            Age = "2074",
                            AllTimeHighUSD = 6.0,
                            Cap = 0.0,
                            Code = "MANA",
                            Color = "#f64e5c",
                            Name = "Decentraland",
                            Rank = 43,
                            Rate = 0.47958734828986094,
                            Volume = 43080300.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mana.png"
                        },
                        new
                        {
                            Uid = "b5890fc7-028c-408a-9ba8-659d6281313b",
                            Age = "929",
                            AllTimeHighUSD = 165.0,
                            Cap = 0.0,
                            Code = "AXS",
                            Color = "#0f48b3",
                            Name = "Axie Infinity",
                            Rank = 44,
                            Rate = 6.936697543604244,
                            Volume = 27002686.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/axs.png"
                        },
                        new
                        {
                            Uid = "48c53df1-efa4-4498-ba62-598ad02ef807",
                            Age = "1698",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "USDP",
                            Color = "#209745",
                            Name = "Pax Dollar",
                            Rank = 45,
                            Rate = 0.99612101154883248,
                            Volume = 76692.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdp.png"
                        },
                        new
                        {
                            Uid = "17cb6ee8-d57b-485c-af00-99e9f3d78680",
                            Age = "630",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "__BIT",
                            Color = "#e44474",
                            Name = "BITDAO",
                            Rank = 46,
                            Rate = 0.51985220010386946,
                            Volume = 5227921.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/__bit.png"
                        },
                        new
                        {
                            Uid = "43645d93-3b68-4d78-bf80-0b46cd5c4dfe",
                            Age = "1010",
                            AllTimeHighUSD = 8.0,
                            Cap = 0.0,
                            Code = "SAND",
                            Color = "#0598f5",
                            Name = "The Sandbox",
                            Rank = 47,
                            Rate = 0.51414934029963189,
                            Volume = 63507557.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sand.png"
                        },
                        new
                        {
                            Uid = "64ce35b5-0b2c-4618-9294-950af872fbbb",
                            Age = "2151",
                            AllTimeHighUSD = 24.0,
                            Cap = 0.0,
                            Code = "EOS",
                            Color = "#ebebeb",
                            Name = "EOS",
                            Rank = 48,
                            Rate = 0.86046210316920857,
                            Volume = 83252040.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eos.png"
                        },
                        new
                        {
                            Uid = "8e901879-3d6c-481c-9d16-a478be6bc499",
                            Age = "951",
                            AllTimeHighUSD = 663.0,
                            Cap = 0.0,
                            Code = "AAVE",
                            Color = "#688cb5",
                            Name = "Aave",
                            Rank = 49,
                            Rate = 65.571873104444123,
                            Volume = 76654661.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/aave.png"
                        },
                        new
                        {
                            Uid = "0ba3ee2b-5a6e-4bd8-bba8-fdd8001e0e0d",
                            Age = "1238",
                            AllTimeHighUSD = 63.0,
                            Cap = 0.0,
                            Code = "RPL",
                            Color = "#fcab71",
                            Name = "Rocket Pool",
                            Rank = 50,
                            Rate = 48.648353858235993,
                            Volume = 7434197.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rpl.png"
                        },
                        new
                        {
                            Uid = "22edcd09-919f-4958-9395-c2745bb61631",
                            Age = "1666",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "FTM",
                            Color = "#e4e4e4",
                            Name = "Fantom",
                            Rank = 51,
                            Rate = 0.3659088456768676,
                            Volume = 74782984.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ftm.png"
                        },
                        new
                        {
                            Uid = "8f975d34-a092-4d10-ba4e-479073ae8589",
                            Age = "991",
                            AllTimeHighUSD = 548.0,
                            Cap = 0.0,
                            Code = "EGLD",
                            Color = "#060606",
                            Name = "MultiversX",
                            Rank = 52,
                            Rate = 36.519397304439778,
                            Volume = 11928252.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/egld.png"
                        },
                        new
                        {
                            Uid = "ff60f42b-f4c4-40ae-a39a-9a6798431dca",
                            Age = "882",
                            AllTimeHighUSD = 2.0,
                            Cap = 0.0,
                            Code = "FRAX",
                            Color = "#040404",
                            Name = "Frax",
                            Rank = 53,
                            Rate = 1.0000835233250345,
                            Volume = 2571795.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/frax.png"
                        },
                        new
                        {
                            Uid = "f69a8bfc-1e0c-4497-9dfc-78201e67c0e4",
                            Age = "1238",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "_STX",
                            Color = "#5546fc",
                            Name = "Stacks",
                            Rank = 54,
                            Rate = 0.63808166635840324,
                            Volume = 31396605.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_stx.png"
                        },
                        new
                        {
                            Uid = "e47c9fd4-b0ce-44b6-98c4-a374bcdb947c",
                            Age = "1952",
                            AllTimeHighUSD = 16.0,
                            Cap = 0.0,
                            Code = "THETA",
                            Color = "#25ced3",
                            Name = "Theta Network",
                            Rank = 55,
                            Rate = 0.87244754209057118,
                            Volume = 7159564.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/theta.png"
                        },
                        new
                        {
                            Uid = "ddadb8b3-11f0-4f3e-b4fe-2345cf30ca64",
                            Age = "1879",
                            AllTimeHighUSD = 9.0,
                            Cap = 0.0,
                            Code = "XTZ",
                            Color = "#2c84fc",
                            Name = "Tezos",
                            Rank = 56,
                            Rate = 0.89245643264711194,
                            Volume = 7523947.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xtz.png"
                        },
                        new
                        {
                            Uid = "cc125331-70ec-4cfc-b14a-122decfd6f23",
                            Age = "1626",
                            AllTimeHighUSD = 29.0,
                            Cap = 0.0,
                            Code = "SNX",
                            Color = "#0f053c",
                            Name = "Synthetix",
                            Rank = 57,
                            Rate = 2.5058288496899315,
                            Volume = 34552187.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/snx.png"
                        },
                        new
                        {
                            Uid = "78150166-f9ac-466d-950c-72c2be9f3c77",
                            Age = "844",
                            AllTimeHighUSD = 42.0,
                            Cap = 0.0,
                            Code = "FLOW",
                            Color = "#f2fcf7",
                            Name = "Flow",
                            Rank = 58,
                            Rate = 0.76638424850551934,
                            Volume = 7409476.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/flow.png"
                        },
                        new
                        {
                            Uid = "4e87a917-50e9-4829-a1e8-f74b4f5f5ae7",
                            Age = "626",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "XRD",
                            Color = "#0427b8",
                            Name = "Radix Native Token",
                            Rank = 59,
                            Rate = 0.074902483190609451,
                            Volume = 2365506.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xrd.png"
                        },
                        new
                        {
                            Uid = "d7f8e41b-31c7-4a15-bb10-e1b4b6c7d5ac",
                            Age = "2446",
                            AllTimeHighUSD = 196.0,
                            Cap = 0.0,
                            Code = "NEO",
                            Color = "#81c425",
                            Name = "NEO",
                            Rank = 60,
                            Rate = 10.297890750750787,
                            Volume = 58174866.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/neo.png"
                        },
                        new
                        {
                            Uid = "acd62f58-e021-4b5d-bef1-e20890a2bdbf",
                            Age = "385",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "USDD",
                            Color = "#e5f0ed",
                            Name = "Decentralized USD",
                            Rank = 61,
                            Rate = 1.0008534532940412,
                            Volume = 39895016.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdd.png"
                        },
                        new
                        {
                            Uid = "40452f22-d6ec-4129-8db0-5ad78a5d94c2",
                            Age = "1904",
                            AllTimeHighUSD = 2.0,
                            Cap = 0.0,
                            Code = "TUSD",
                            Color = "#6eb6fc",
                            Name = "True USD",
                            Rank = 62,
                            Rate = 1.0011578047671961,
                            Volume = 61486670.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/tusd.png"
                        },
                        new
                        {
                            Uid = "7a29bb1a-acae-4609-89b0-9a2e46f5efb1",
                            Age = "1010",
                            AllTimeHighUSD = 7.0,
                            Cap = 0.0,
                            Code = "CRV",
                            Color = "#d3e226",
                            Name = "Curve DAO Token",
                            Rank = 63,
                            Rate = 0.87159673534283755,
                            Volume = 35488863.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/crv.png"
                        },
                        new
                        {
                            Uid = "b9778d20-88ad-43fa-a079-e857de7ce4be",
                            Age = "",
                            AllTimeHighUSD = 15.0,
                            Cap = 0.0,
                            Code = "WBT",
                            Color = "#f7df5c",
                            Name = "WhiteBIT Token",
                            Rank = 64,
                            Rate = 4.6203385745856496,
                            Volume = 21393318.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/wbt.png"
                        },
                        new
                        {
                            Uid = "cc823c26-9872-441a-ab30-ad49a9be7452",
                            Age = "981",
                            AllTimeHighUSD = 13.0,
                            Cap = 0.0,
                            Code = "GT",
                            Color = "#d45454",
                            Name = "Gatechain Token",
                            Rank = 65,
                            Rate = 4.8936691810532533,
                            Volume = 531518.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/gt.png"
                        },
                        new
                        {
                            Uid = "58cc6ba8-9017-40ae-a2bb-ffee76b2b755",
                            Age = "36",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "____PEPE",
                            Color = "#38792e",
                            Name = "Pepe",
                            Rank = 66,
                            Rate = 1.608243733762202E-06,
                            Volume = 174227570.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/____pepe.png"
                        },
                        new
                        {
                            Uid = "d3bb00ed-4dbb-4c4e-a110-c83a37bb0006",
                            Age = "924",
                            AllTimeHighUSD = 2.0,
                            Cap = 0.0,
                            Code = "CFX",
                            Color = "#418390",
                            Name = "Conflux Token",
                            Rank = 67,
                            Rate = 0.31770728271703097,
                            Volume = 310231927.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cfx.png"
                        },
                        new
                        {
                            Uid = "595f8f9a-e032-4352-a375-40b7c8540cbf",
                            Age = "1650",
                            AllTimeHighUSD = 491.0,
                            Cap = 0.0,
                            Code = "BSV",
                            Color = "#ebb304",
                            Name = "Bitcoin SV",
                            Rank = 68,
                            Rate = 34.1722204253253,
                            Volume = 14518967.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bsv.png"
                        },
                        new
                        {
                            Uid = "79bf13d1-9b2a-48fe-9ff1-fb0afc93cc1d",
                            Age = "1238",
                            AllTimeHighUSD = 9.0,
                            Cap = 0.0,
                            Code = "KAVA",
                            Color = "#fc544c",
                            Name = "Kava",
                            Rank = 69,
                            Rate = 1.2016537091037065,
                            Volume = 236678383.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kava.png"
                        },
                        new
                        {
                            Uid = "b3144549-430f-462c-ac09-05cf56c417bd",
                            Age = "1934",
                            AllTimeHighUSD = 40.0,
                            Cap = 0.0,
                            Code = "HT",
                            Color = "#049cdc",
                            Name = "Huobi Token",
                            Rank = 70,
                            Rate = 3.0931249361663453,
                            Volume = 31519120.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ht.png"
                        },
                        new
                        {
                            Uid = "49ddc397-fbfc-450f-9844-ebd3583b55cd",
                            Age = "2304",
                            AllTimeHighUSD = 6299.0,
                            Cap = 0.0,
                            Code = "MKR",
                            Color = "#1cac9c",
                            Name = "Maker",
                            Rank = 71,
                            Rate = 631.288883001969,
                            Volume = 7210084.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mkr.png"
                        },
                        new
                        {
                            Uid = "12f26318-3abf-4eec-bb9c-a119eb67cc7f",
                            Age = "2316",
                            AllTimeHighUSD = 119.0,
                            Cap = 0.0,
                            Code = "LUNC",
                            Color = "#fbd35b",
                            Name = "Luna Classic",
                            Rank = 72,
                            Rate = 8.9747923139433391E-05,
                            Volume = 26345071.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/lunc.png"
                        },
                        new
                        {
                            Uid = "ce99c749-6d96-430e-9afd-2a4b324e9d64",
                            Age = "1572",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "BTT",
                            Color = "#f3f3f3",
                            Name = "BitTorrent",
                            Rank = 73,
                            Rate = 5.9819192079022792E-07,
                            Volume = 9890561.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btt.png"
                        },
                        new
                        {
                            Uid = "193dbd93-9433-4a30-9ed1-764c4858d88a",
                            Age = "782",
                            AllTimeHighUSD = 4.0,
                            Cap = 0.0,
                            Code = "_KLAY",
                            Color = "#1c1c1c",
                            Name = "Klaytn",
                            Rank = 74,
                            Rate = 0.18289388365478398,
                            Volume = 7922669.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_klay.png"
                        },
                        new
                        {
                            Uid = "c2c10e9c-acc7-4827-b8cb-947a988b1a03",
                            Age = "2036",
                            AllTimeHighUSD = 28.0,
                            Cap = 0.0,
                            Code = "KCS",
                            Color = "#24ac94",
                            Name = "KuCoin Shares",
                            Rank = 75,
                            Rate = 7.4236297637238398,
                            Volume = 807958.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/kcs.png"
                        },
                        new
                        {
                            Uid = "4ddd2a12-174c-4543-afa6-74ca0723c2c0",
                            Age = "1412",
                            AllTimeHighUSD = 1.0,
                            Cap = 0.0,
                            Code = "CHZ",
                            Color = "#cc0524",
                            Name = "Chiliz",
                            Rank = 76,
                            Rate = 0.10496896438406707,
                            Volume = 23612246.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/chz.png"
                        },
                        new
                        {
                            Uid = "77e019a1-5364-45cd-b21f-a4472dc6797c",
                            Age = "943",
                            AllTimeHighUSD = 25.0,
                            Cap = 0.0,
                            Code = "INJ",
                            Color = "#04a7fc",
                            Name = "Injective Protocol",
                            Rank = 77,
                            Rate = 6.8293272485889398,
                            Volume = 89008528.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/inj.png"
                        },
                        new
                        {
                            Uid = "3f88e832-944f-4d08-ab96-5d170c128669",
                            Age = "746",
                            AllTimeHighUSD = 40.0,
                            Cap = 0.0,
                            Code = "CSPR",
                            Color = "#fc443c",
                            Name = "Casper Network",
                            Rank = 78,
                            Rate = 0.048993895184271344,
                            Volume = 2771474.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cspr.png"
                        },
                        new
                        {
                            Uid = "34d03d26-73a7-4794-b20f-071462d83390",
                            Age = "2396",
                            AllTimeHighUSD = 2218.0,
                            Cap = 0.0,
                            Code = "ZEC",
                            Color = "#e4a93d",
                            Name = "Zcash",
                            Rank = 79,
                            Rate = 32.463004192300339,
                            Volume = 14319672.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/zec.png"
                        },
                        new
                        {
                            Uid = "6ed1b57c-c8b2-468f-898b-6b4a16e0b1a2",
                            Age = "2169",
                            AllTimeHighUSD = 6.0,
                            Cap = 0.0,
                            Code = "MIOTA",
                            Color = "#040404",
                            Name = "IOTA",
                            Rank = 80,
                            Rate = 0.18961143108205691,
                            Volume = 5881036.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/miota.png"
                        },
                        new
                        {
                            Uid = "1e607a9c-aade-4e06-969d-67c8d28301b3",
                            Age = "767",
                            AllTimeHighUSD = 188.0,
                            Cap = 0.0,
                            Code = "MINA",
                            Color = "#bf91b1",
                            Name = "Mina Protocol",
                            Rank = 81,
                            Rate = 0.58103133975476839,
                            Volume = 9103539.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/mina.png"
                        },
                        new
                        {
                            Uid = "d91de867-9295-427e-9371-fbded1655ac6",
                            Age = "1335",
                            AllTimeHighUSD = 2222.0,
                            Cap = 0.0,
                            Code = "PAXG",
                            Color = "#ebe318",
                            Name = "PAX Gold",
                            Rank = 82,
                            Rate = 1986.2549258836252,
                            Volume = 8948510.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/paxg.png"
                        },
                        new
                        {
                            Uid = "19773f9b-21c7-48f0-a08c-0abfc6f5e9ed",
                            Age = "882",
                            AllTimeHighUSD = 45.0,
                            Cap = 0.0,
                            Code = "FXS",
                            Color = "#0c0c0c",
                            Name = "Frax Share",
                            Rank = 83,
                            Rate = 7.0573183792658591,
                            Volume = 11932384.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/fxs.png"
                        },
                        new
                        {
                            Uid = "49200c72-fe86-40f8-a48a-189147a3840e",
                            Age = "3384",
                            AllTimeHighUSD = 1642.0,
                            Cap = 0.0,
                            Code = "DASH",
                            Color = "#048ce4",
                            Name = "Dash",
                            Rank = 84,
                            Rate = 44.024384017511686,
                            Volume = 36889673.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/dash.png"
                        },
                        new
                        {
                            Uid = "40fc9d31-5cf2-4827-b132-d80e7a25a0e4",
                            Age = "689",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "XEC",
                            Color = "#066fbf",
                            Name = "eCash",
                            Rank = 85,
                            Rate = 2.5604853451274866E-05,
                            Volume = 1210850.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xec.png"
                        },
                        new
                        {
                            Uid = "76814d86-6174-4cbc-84ac-6f343a01defc",
                            Age = "603",
                            AllTimeHighUSD = 91.0,
                            Cap = 0.0,
                            Code = "__GMX",
                            Color = "#1395ea",
                            Name = "GMX",
                            Rank = 86,
                            Rate = 58.915819410433485,
                            Volume = 14141296.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/__gmx.png"
                        },
                        new
                        {
                            Uid = "0712aba2-25d0-4ae6-abde-0be837e8f224",
                            Age = "845",
                            AllTimeHighUSD = 2.0,
                            Cap = 0.0,
                            Code = "FLR",
                            Color = "#cc92a6",
                            Name = "Flare",
                            Rank = 87,
                            Rate = 0.028003896309268899,
                            Volume = 2149013.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/flr.png"
                        },
                        new
                        {
                            Uid = "a80c9bb6-b651-4d03-90ce-4525c0955125",
                            Age = "1878",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "XDC",
                            Color = "#254d84",
                            Name = "XDC Network",
                            Rank = 88,
                            Rate = 0.031919445532237974,
                            Volume = 1329613.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/xdc.png"
                        },
                        new
                        {
                            Uid = "93c07637-8368-42b2-bfb7-b15799d0dd55",
                            Age = "560",
                            AllTimeHighUSD = 84.0,
                            Cap = 0.0,
                            Code = "ENS",
                            Color = "#69a1f6",
                            Name = "Ethereum Name Service",
                            Rank = 89,
                            Rate = 10.336572207236232,
                            Volume = 5686802.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/ens.png"
                        },
                        new
                        {
                            Uid = "48010944-33ee-4554-85ee-6682d912793d",
                            Age = "830",
                            AllTimeHighUSD = 20.0,
                            Cap = 0.0,
                            Code = "ROUTE",
                            Color = "#ece2e4",
                            Name = "Router Protocol",
                            Rank = 90,
                            Rate = 2.8445444290939279,
                            Volume = 521829.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/route.png"
                        },
                        new
                        {
                            Uid = "76b16a6a-ae9a-4065-a4c4-71ae1307fb67",
                            Age = "715",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "BABYDOGE",
                            Color = "#e19f4c",
                            Name = "Baby Doge Coin",
                            Rank = 91,
                            Rate = 1.9269580541265252E-09,
                            Volume = 6275754.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/babydoge.png"
                        },
                        new
                        {
                            Uid = "295dd127-dea8-4aea-8715-86fd667e1f70",
                            Age = "1228",
                            AllTimeHighUSD = 0.0,
                            Cap = 0.0,
                            Code = "_SURE",
                            Color = "#c38cfc",
                            Name = "inSure",
                            Rank = 92,
                            Rate = 0.0046091855895890425,
                            Volume = 3144663.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/_sure.png"
                        },
                        new
                        {
                            Uid = "3131639b-b059-414a-ab8b-3d1f3cd777bc",
                            Age = "2091",
                            AllTimeHighUSD = 4.0,
                            Cap = 0.0,
                            Code = "LRC",
                            Color = "#040404",
                            Name = "Loopring",
                            Rank = 93,
                            Rate = 0.29482866079901615,
                            Volume = 7497173.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/lrc.png"
                        },
                        new
                        {
                            Uid = "3084f4aa-c6aa-4b57-bc44-30c50fc9ba56",
                            Age = "1399",
                            AllTimeHighUSD = 21.0,
                            Cap = 0.0,
                            Code = "RUNE",
                            Color = "#34fcb4",
                            Name = "THORChain",
                            Rank = 94,
                            Rate = 1.147406174666888,
                            Volume = 26635949.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/rune.png"
                        },
                        new
                        {
                            Uid = "5439fa53-ac7a-4eb8-a2c8-ff8d434ddda3",
                            Age = "1025",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "TWT",
                            Color = "#045454",
                            Name = "Trust Wallet Token",
                            Rank = 95,
                            Rate = 1.0836082331494823,
                            Volume = 8105098.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/twt.png"
                        },
                        new
                        {
                            Uid = "1b176e52-f135-483c-b33b-f6a5c7453709",
                            Age = "1847",
                            AllTimeHighUSD = 5.0,
                            Cap = 0.0,
                            Code = "NEXO",
                            Color = "#bdd7e9",
                            Name = "Nexo",
                            Rank = 96,
                            Rate = 0.66833721726009365,
                            Volume = 2407047.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/nexo.png"
                        },
                        new
                        {
                            Uid = "43037f7c-eafe-4511-94f2-07cdc9d9a400",
                            Age = "903",
                            AllTimeHighUSD = 2.0,
                            Cap = 0.0,
                            Code = "WOO",
                            Color = "#0d1c25",
                            Name = "Wootrade Network",
                            Rank = 97,
                            Rate = 0.21587375278728937,
                            Volume = 20899791.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/woo.png"
                        },
                        new
                        {
                            Uid = "48c717c0-6ef8-4cad-9615-bfa52365da4f",
                            Age = "956",
                            AllTimeHighUSD = 44.0,
                            Cap = 0.0,
                            Code = "CAKE",
                            Color = "#945d28",
                            Name = "PancakeSwap",
                            Rank = 98,
                            Rate = 1.8050042670079516,
                            Volume = 20286349.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cake.png"
                        },
                        new
                        {
                            Uid = "7af9c914-8dfc-4eba-ba5e-9e3a1d6e681a",
                            Age = "356",
                            AllTimeHighUSD = 3.0,
                            Cap = 0.0,
                            Code = "OP",
                            Color = "#fc0424",
                            Name = "Optimism",
                            Rank = 99,
                            Rate = 1.6689780977141815,
                            Volume = 98408542.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/op.png"
                        },
                        new
                        {
                            Uid = "c82150d4-927a-4336-a019-a7ac2caade9a",
                            Age = "733",
                            AllTimeHighUSD = 60.0,
                            Cap = 0.0,
                            Code = "CVX",
                            Color = "#3c474c",
                            Name = "Convex Finance",
                            Rank = 100,
                            Rate = 4.6204866487179705,
                            Volume = 4887053.0,
                            png64 = "https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/cvx.png"
                        });
                });

            modelBuilder.Entity("InvestmentApp.API.Models.SiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2577b041-882d-4867-b832-9e5e0d8d4f3b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e14d9efc-a442-402a-a955-87bb9914dec8",
                            Email = "admin@admin.adm",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAELiuMgur08QgW/rUQ9slHvQWnNG/AYUjFDJIu3y3nNibpHoCvcCg2Ix+AOVJFZLTGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0bc7a93d-74d5-435e-ba10-8f68a8b34d47",
                            TwoFactorEnabled = false,
                            UserName = "superuser"
                        });
                });

            modelBuilder.Entity("InvestmentApp.API.Models.UserCoins", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoinId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CoinCount")
                        .HasColumnType("float");

                    b.Property<string>("SiteUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "CoinId");

                    b.HasIndex("CoinId");

                    b.HasIndex("SiteUserId");

                    b.ToTable("UserCoins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "I",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InvestmentApp.API.Models.UserCoins", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany("Coins")
                        .HasForeignKey("SiteUserId");

                    b.Navigation("Coin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InvestmentApp.API.Models.SiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestmentApp.API.Models.SiteUser", b =>
                {
                    b.Navigation("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
